import {
 assertPolicyAuthorizedRepositoryContext,
 type ArchiveItemRow,
 type ArchiveVersionRow,
 type ArchiveRepositoryPort,
 type ArchivePolicyResourceRepositoryPort,
 type PolicyAuthorizedRepositoryExecutionContext,
 type RepositoryExecutionContext,
 type RepositoryResult
} from '@ppt/repository-contracts';
import type { ArchiveItemView, ArchiveVersionView, ArchiveRetentionPolicyView, ArchiveRetentionStatusView, ArchiveCategoryView, ArchiveClassificationView, ArchiveSensitivity } from '@ppt/domain';
import { SqliteRepository } from './sqlite-base.js';
import { platformPolicyPersistenceBinding } from './platform-policy-transaction-repository.js';
const item=(r:Record<string,unknown>):ArchiveItemRow=>({id:String(r.id),familyId:String(r.family_id),...(r.owner_person_id?{ownerPersonId:String(r.owner_person_id)}:{}),title:String(r.title),originalName:String(r.original_name),storedName:String(r.stored_name),mimeType:String(r.mime_type),sizeBytes:Number(r.size_bytes),sha256:String(r.sha256),createdAt:String(r.created_at),...(r.linked_event_id?{linkedEventId:String(r.linked_event_id)}:{}),...(r.category_id?{categoryId:String(r.category_id)}:{}),sensitivity:String(r.sensitivity||'standard') as ArchiveItemRow['sensitivity'],aiProcessingAllowed:Number(r.ai_processing_allowed)===1});
const version=(r:Record<string,unknown>):ArchiveVersionRow=>({id:String(r.id),archiveItemId:String(r.archive_item_id),versionNo:Number(r.version_no),originalName:String(r.original_name),storedName:String(r.stored_name||''),mimeType:String(r.mime_type),sizeBytes:Number(r.size_bytes),sha256:String(r.sha256),createdAt:String(r.created_at),...(r.note?{note:String(r.note)}:{})});
const exactPolicyBinding=(context:PolicyAuthorizedRepositoryExecutionContext,resourceType:'archive_item'|'archive_retention_policy'|'archive_category',resourceId:string,action:'create'|'update'|'delete')=>{assertPolicyAuthorizedRepositoryContext(context,{resourceType,resourceId,action,capability:'archive.write',correlationId:context.correlationId});const binding=platformPolicyPersistenceBinding(context,resourceType,resourceId);if(!binding)throw new Error('Archive write requires an active platform policy receipt binding');return binding;};
const archivePolicyBinding=(context:PolicyAuthorizedRepositoryExecutionContext,resourceId:string,action:'create'|'update'|'delete')=>exactPolicyBinding(context,'archive_item',resourceId,action);
const exactReadBinding=(context:PolicyAuthorizedRepositoryExecutionContext,resourceType:'archive_item'|'archive_collection',resourceId:string)=>assertPolicyAuthorizedRepositoryContext(context,{resourceType,resourceId,action:'read',capability:'archive.read',correlationId:context.correlationId});
const collectionReadBinding=(context:PolicyAuthorizedRepositoryExecutionContext)=>exactReadBinding(context,'archive_collection',context.policyAuthorization.resourceId);

export class SqliteArchiveRepository extends SqliteRepository implements ArchiveRepositoryPort, ArchivePolicyResourceRepositoryPort {
 list(context:PolicyAuthorizedRepositoryExecutionContext):RepositoryResult<readonly ArchiveItemRow[]>{collectionReadBinding(context);return this.listForPolicyResolution(context);}
 listForPolicyResolution(context:RepositoryExecutionContext):RepositoryResult<readonly ArchiveItemRow[]>{return this.execute(context,()=> (this.database(context).prepare("SELECT a.id,a.family_id,json_extract(receipt.record_json,'$.request.resource.ownerPersonId') owner_person_id,a.title,a.original_name,a.stored_name,a.mime_type,a.size_bytes,a.sha256,a.linked_event_id,a.category_id,a.sensitivity,a.ai_processing_allowed,a.created_at FROM archive_items a LEFT JOIN platform_policy_transaction_receipts receipt ON receipt.receipt_hash=a.policy_receipt_hash WHERE a.destroyed_at IS NULL ORDER BY a.created_at DESC,a.id").all() as Array<Record<string,unknown>>).map(item));}
 search(context:PolicyAuthorizedRepositoryExecutionContext,input:{query:string;categoryId:string;sensitivity:string;tag:string;mimeType:string;linkedEventId:string}):RepositoryResult<readonly ArchiveItemRow[]>{collectionReadBinding(context);return this.execute(context,()=>{const rows=this.database(context).prepare("SELECT a.id,a.family_id,json_extract(receipt.record_json,'$.request.resource.ownerPersonId') owner_person_id,a.title,a.original_name,a.stored_name,a.mime_type,a.size_bytes,a.sha256,a.linked_event_id,a.category_id,a.sensitivity,a.ai_processing_allowed,a.created_at,group_concat(t.name,'|') tags FROM archive_items a LEFT JOIN platform_policy_transaction_receipts receipt ON receipt.receipt_hash=a.policy_receipt_hash LEFT JOIN archive_item_tags it ON it.archive_item_id=a.id LEFT JOIN archive_tags t ON t.id=it.tag_id WHERE a.destroyed_at IS NULL GROUP BY a.id ORDER BY a.created_at DESC,a.id").all() as Array<Record<string,unknown>>;return rows.filter(r=>!input.query||[r.title,r.original_name,r.mime_type,r.tags].some(v=>String(v??'').toLocaleLowerCase('tr-TR').includes(input.query))).filter(r=>!input.categoryId||String(r.category_id??'')===input.categoryId).filter(r=>!input.sensitivity||String(r.sensitivity??'standard')===input.sensitivity).filter(r=>!input.tag||String(r.tags??'').toLocaleLowerCase('tr-TR').split('|').some(x=>x.includes(input.tag))).filter(r=>!input.mimeType||String(r.mime_type).includes(input.mimeType)).filter(r=>!input.linkedEventId||String(r.linked_event_id??'')===input.linkedEventId).map(item);});}
 find(context:PolicyAuthorizedRepositoryExecutionContext,id:string):RepositoryResult<ArchiveItemRow|null>{exactReadBinding(context,'archive_item',id);return this.findForPolicyResolution(context,id);}
 findForPolicyResolution(context:RepositoryExecutionContext,id:string):RepositoryResult<ArchiveItemRow|null>{return this.execute(context,()=>{const r=this.database(context).prepare("SELECT a.id,a.family_id,json_extract(receipt.record_json,'$.request.resource.ownerPersonId') owner_person_id,a.title,a.original_name,a.stored_name,a.mime_type,a.size_bytes,a.sha256,a.linked_event_id,a.category_id,a.sensitivity,a.ai_processing_allowed,a.created_at FROM archive_items a LEFT JOIN platform_policy_transaction_receipts receipt ON receipt.receipt_hash=a.policy_receipt_hash WHERE a.id=? AND a.destroyed_at IS NULL").get(id) as Record<string,unknown>|undefined;return r?item(r):null;});}
 insert(context:PolicyAuthorizedRepositoryExecutionContext,row:ArchiveItemRow):RepositoryResult<void>{const p=archivePolicyBinding(context,row.id,'create');return this.execute(context,()=>{this.database(context).prepare('INSERT INTO archive_items(id,family_id,title,original_name,stored_name,mime_type,size_bytes,sha256,linked_event_id,category_id,sensitivity,ai_processing_allowed,created_at,policy_receipt_hash,policy_receipt_version,policy_receipt_nonce,policy_correlation_id,policy_resource_type,policy_resource_id,policy_action,policy_capability) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run(row.id,row.familyId,row.title,row.originalName,row.storedName,row.mimeType,row.sizeBytes,row.sha256,row.linkedEventId??null,row.categoryId??null,row.sensitivity,row.aiProcessingAllowed?1:0,row.createdAt,p.receiptHash,p.receiptVersion,p.nonce,context.correlationId,p.resourceType,p.resourceId,p.action,p.capability);});}
 insertVersion(context:PolicyAuthorizedRepositoryExecutionContext,row:ArchiveVersionRow):RepositoryResult<void>{const p=archivePolicyBinding(context,row.archiveItemId,'create');return this.execute(context,()=>{this.database(context).prepare('INSERT INTO archive_versions(id,archive_item_id,version_no,original_name,stored_name,mime_type,size_bytes,sha256,created_at,note,policy_receipt_hash,policy_receipt_version,policy_receipt_nonce,policy_correlation_id,policy_resource_type,policy_resource_id,policy_action,policy_capability) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run(row.id,row.archiveItemId,row.versionNo,row.originalName,row.storedName,row.mimeType,row.sizeBytes,row.sha256,row.createdAt,row.note??null,p.receiptHash,p.receiptVersion,p.nonce,context.correlationId,p.resourceType,p.resourceId,p.action,p.capability);});}
 listVersions(context:PolicyAuthorizedRepositoryExecutionContext,itemId:string):RepositoryResult<readonly ArchiveVersionRow[]>{exactReadBinding(context,'archive_item',itemId);return this.listVersionsForPolicyResolution(context,itemId);}
 listVersionsForPolicyResolution(context:RepositoryExecutionContext,itemId:string):RepositoryResult<readonly ArchiveVersionRow[]>{return this.execute(context,()=> (this.database(context).prepare('SELECT id,archive_item_id,version_no,original_name,stored_name,mime_type,size_bytes,sha256,created_at,note FROM archive_versions WHERE archive_item_id=? ORDER BY version_no DESC').all(itemId) as Array<Record<string,unknown>>).map(version));}

 listRetentionPolicies(context:PolicyAuthorizedRepositoryExecutionContext):RepositoryResult<readonly ArchiveRetentionPolicyView[]>{collectionReadBinding(context);return this.listRetentionPoliciesForPolicyResolution(context);}
 listRetentionPoliciesForPolicyResolution(context:RepositoryExecutionContext):RepositoryResult<readonly ArchiveRetentionPolicyView[]>{return this.execute(context,()=> (this.database(context).prepare('SELECT id,name,retention_days,secure_destroy,created_at FROM archive_retention_policies ORDER BY name COLLATE NOCASE').all() as Array<Record<string,unknown>>).map(r=>({id:String(r.id),name:String(r.name),retentionDays:Number(r.retention_days),secureDestroy:Number(r.secure_destroy)===1,createdAt:String(r.created_at)})));}
 insertRetentionPolicy(context:PolicyAuthorizedRepositoryExecutionContext,row:ArchiveRetentionPolicyView):RepositoryResult<void>{const p=exactPolicyBinding(context,'archive_retention_policy',row.id,'create');return this.execute(context,()=>{this.database(context).prepare('INSERT INTO archive_retention_policies(id,name,retention_days,secure_destroy,created_at,policy_receipt_hash,policy_receipt_version,policy_receipt_nonce,policy_correlation_id,policy_resource_type,policy_resource_id,policy_action,policy_capability) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)').run(row.id,row.name,row.retentionDays,row.secureDestroy?1:0,row.createdAt,p.receiptHash,p.receiptVersion,p.nonce,context.correlationId,p.resourceType,p.resourceId,p.action,p.capability);});}
 assignRetentionPolicy(context:PolicyAuthorizedRepositoryExecutionContext,itemId:string,policyId:string|null):RepositoryResult<void>{const p=archivePolicyBinding(context,itemId,'update');return this.execute(context,()=>{if(policyId){const found=this.database(context).prepare('SELECT 1 FROM archive_retention_policies WHERE id=?').get(policyId);if(!found)throw new Error('Saklama politikası bulunamadı.');}const x=this.database(context).prepare('UPDATE archive_items SET retention_policy_id=?,policy_receipt_hash=?,policy_receipt_version=?,policy_receipt_nonce=?,policy_correlation_id=?,policy_resource_type=?,policy_resource_id=?,policy_action=?,policy_capability=? WHERE id=? AND destroyed_at IS NULL').run(policyId,p.receiptHash,p.receiptVersion,p.nonce,context.correlationId,p.resourceType,p.resourceId,p.action,p.capability,itemId);if(x.changes!==1)throw new Error('Arşiv kaydı bulunamadı.');});}
 listRetentionStatus(context:PolicyAuthorizedRepositoryExecutionContext):RepositoryResult<readonly ArchiveRetentionStatusView[]>{collectionReadBinding(context);return this.listRetentionStatusForPolicyResolution(context);}
 listRetentionStatusForPolicyResolution(context:RepositoryExecutionContext):RepositoryResult<readonly ArchiveRetentionStatusView[]>{return this.execute(context,()=>{const now=Date.parse(context.occurredAt);return (this.database(context).prepare('SELECT a.id item_id,a.created_at,a.destroyed_at,p.id policy_id,p.name policy_name,p.retention_days FROM archive_items a LEFT JOIN archive_retention_policies p ON p.id=a.retention_policy_id ORDER BY a.created_at DESC').all() as Array<Record<string,unknown>>).map(r=>{const retainUntil=r.retention_days?new Date(Date.parse(String(r.created_at))+Number(r.retention_days)*86400000).toISOString():undefined;return {itemId:String(r.item_id),...(r.policy_id&&retainUntil?{policyId:String(r.policy_id),policyName:String(r.policy_name),retainUntil}:{}),eligibleForDestruction:!!retainUntil&&Date.parse(retainUntil)<=now&&!r.destroyed_at,...(r.destroyed_at?{destroyedAt:String(r.destroyed_at)}:{})};});});}
 getDestructionPlan(context:PolicyAuthorizedRepositoryExecutionContext,itemId:string):RepositoryResult<{storedName:string;secureDestroy:boolean}|null>{archivePolicyBinding(context,itemId,'delete');return this.execute(context,()=>{const r=this.database(context).prepare('SELECT a.stored_name,a.destroyed_at,a.created_at,p.retention_days,p.secure_destroy FROM archive_items a LEFT JOIN archive_retention_policies p ON p.id=a.retention_policy_id WHERE a.id=?').get(itemId) as Record<string,unknown>|undefined;if(!r)return null;if(r.destroyed_at)throw new Error('Kayıt daha önce imha edilmiş.');if(!r.retention_days)throw new Error('Saklama politikası atanmamış.');if(Date.parse(context.occurredAt)<Date.parse(String(r.created_at))+Number(r.retention_days)*86400000)throw new Error('Saklama süresi henüz dolmadı.');return {storedName:String(r.stored_name),secureDestroy:Number(r.secure_destroy)===1};});}
 markDestroyed(context:PolicyAuthorizedRepositoryExecutionContext,itemId:string,destroyedAt:string):RepositoryResult<void>{const p=archivePolicyBinding(context,itemId,'delete');return this.execute(context,()=>{const x=this.database(context).prepare('UPDATE archive_items SET destroyed_at=?,policy_receipt_hash=?,policy_receipt_version=?,policy_receipt_nonce=?,policy_correlation_id=?,policy_resource_type=?,policy_resource_id=?,policy_action=?,policy_capability=? WHERE id=? AND destroyed_at IS NULL').run(destroyedAt,p.receiptHash,p.receiptVersion,p.nonce,context.correlationId,p.resourceType,p.resourceId,p.action,p.capability,itemId);if(x.changes!==1)throw new Error('Arşiv kaydı bulunamadı veya daha önce imha edilmiş.');});}

 listCategories(context:PolicyAuthorizedRepositoryExecutionContext):RepositoryResult<readonly ArchiveCategoryView[]>{collectionReadBinding(context);return this.listCategoriesForPolicyResolution(context);}
 listCategoriesForPolicyResolution(context:RepositoryExecutionContext):RepositoryResult<readonly ArchiveCategoryView[]>{return this.execute(context,()=> (this.database(context).prepare('SELECT id,name,description,created_at FROM archive_categories ORDER BY name COLLATE NOCASE').all() as Array<Record<string,unknown>>).map(r=>({id:String(r.id),name:String(r.name),...(r.description?{description:String(r.description)}:{}),createdAt:String(r.created_at)})));}
 insertCategory(context:PolicyAuthorizedRepositoryExecutionContext,row:ArchiveCategoryView):RepositoryResult<void>{const p=exactPolicyBinding(context,'archive_category',row.id,'create');return this.execute(context,()=>{this.database(context).prepare('INSERT INTO archive_categories(id,name,description,created_at,policy_receipt_hash,policy_receipt_version,policy_receipt_nonce,policy_correlation_id,policy_resource_type,policy_resource_id,policy_action,policy_capability) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)').run(row.id,row.name,row.description??null,row.createdAt,p.receiptHash,p.receiptVersion,p.nonce,context.correlationId,p.resourceType,p.resourceId,p.action,p.capability);});}
 listClassifications(context:PolicyAuthorizedRepositoryExecutionContext):RepositoryResult<readonly ArchiveClassificationView[]>{collectionReadBinding(context);return this.listClassificationsForPolicyResolution(context);}
 listClassificationsForPolicyResolution(context:RepositoryExecutionContext):RepositoryResult<readonly ArchiveClassificationView[]>{return this.execute(context,()=>{const rows=this.database(context).prepare('SELECT a.id item_id,a.category_id,c.name category_name,a.sensitivity,a.ai_processing_allowed FROM archive_items a LEFT JOIN archive_categories c ON c.id=a.category_id WHERE a.destroyed_at IS NULL ORDER BY a.created_at DESC').all() as Array<Record<string,unknown>>;const tq=this.database(context).prepare('SELECT t.id,t.name,t.created_at FROM archive_item_tags it JOIN archive_tags t ON t.id=it.tag_id WHERE it.archive_item_id=? ORDER BY t.name COLLATE NOCASE');return rows.map(r=>({itemId:String(r.item_id),...(r.category_id?{categoryId:String(r.category_id)}:{}),...(r.category_name?{categoryName:String(r.category_name)}:{}),tags:(tq.all(String(r.item_id)) as Array<Record<string,unknown>>).map(t=>({id:String(t.id),name:String(t.name),createdAt:String(t.created_at)})),sensitivity:String(r.sensitivity||'standard') as ArchiveSensitivity,aiProcessingAllowed:Number(r.ai_processing_allowed)===1}));});}
 updateClassification(context:PolicyAuthorizedRepositoryExecutionContext,input:{itemId:string;categoryId:string|null;sensitivity:ArchiveSensitivity;aiProcessingAllowed:boolean;tags:readonly {id:string;name:string}[]}):RepositoryResult<void>{const p=archivePolicyBinding(context,input.itemId,'update');return this.execute(context,()=>{if(input.categoryId&&!this.database(context).prepare('SELECT 1 FROM archive_categories WHERE id=?').get(input.categoryId))throw new Error('Arşiv kategorisi bulunamadı.');const changed=this.database(context).prepare('UPDATE archive_items SET category_id=?,sensitivity=?,ai_processing_allowed=?,policy_receipt_hash=?,policy_receipt_version=?,policy_receipt_nonce=?,policy_correlation_id=?,policy_resource_type=?,policy_resource_id=?,policy_action=?,policy_capability=? WHERE id=? AND destroyed_at IS NULL').run(input.categoryId,input.sensitivity,input.aiProcessingAllowed?1:0,p.receiptHash,p.receiptVersion,p.nonce,context.correlationId,p.resourceType,p.resourceId,p.action,p.capability,input.itemId);if(changed.changes!==1)throw new Error('Arşiv kaydı bulunamadı.');this.database(context).prepare('INSERT INTO platform_policy_archive_classification_batches(receipt_hash,receipt_version,receipt_nonce,correlation_id,archive_item_id,resource_type,resource_id,action,capability,desired_tags_json,opened_at) SELECT ?,?,?,?,?,?,?,?,?,?,receipt.recorded_at FROM platform_policy_transaction_receipts receipt WHERE receipt.receipt_hash=?').run(p.receiptHash,p.receiptVersion,p.nonce,context.correlationId,input.itemId,p.resourceType,p.resourceId,p.action,p.capability,JSON.stringify(input.tags),p.receiptHash);const batch=this.database(context).prepare('SELECT status FROM platform_policy_archive_classification_batches WHERE receipt_hash=?').get(p.receiptHash) as {status?:string}|undefined;if(batch?.status!=='sealed')throw new Error('Arşiv sınıflandırma receipt batch kaydı mühürlenemedi.');});}
 incrementEventAttachment(context:PolicyAuthorizedRepositoryExecutionContext,eventId:string):RepositoryResult<void>{const p=archivePolicyBinding(context,context.policyAuthorization.resourceId,'create');return this.execute(context,()=>{const x=this.database(context).prepare('UPDATE events SET attachment_count=attachment_count+1,policy_receipt_hash=?,policy_receipt_version=?,policy_receipt_nonce=?,policy_correlation_id=?,policy_resource_type=?,policy_resource_id=?,policy_action=?,policy_capability=? WHERE id=?').run(p.receiptHash,p.receiptVersion,p.nonce,context.correlationId,p.resourceType,p.resourceId,p.action,p.capability,eventId);if(x.changes!==1)throw new Error('Bağlı etkinlik bulunamadı.');});}
}
