import type { BackupRepositoryPort } from '@ppt/repository-contracts';
import type { BackupRunView, BackupTargetView } from '@ppt/domain';
import type { RepositoryResult } from '@ppt/repository-contracts';
import { SqliteRepository } from './sqlite-base.js';
import type { RepositoryExecutionContext } from '@ppt/repository-contracts';
const target=(r:Record<string,unknown>):BackupTargetView=>({id:String(r.id),name:String(r.name),kind:String(r.kind) as BackupTargetView['kind'],path:String(r.path),enabled:Boolean(r.enabled),schedule:String(r.schedule??'manual') as BackupTargetView['schedule'],retentionCount:Number(r.retention_count??10),retryCount:Number(r.retry_count??2),createdAt:String(r.created_at),...(r.next_run_at?{nextRunAt:String(r.next_run_at)}:{}),...(r.last_success_at?{lastSuccessAt:String(r.last_success_at)}:{}),...(r.last_verified_at?{lastVerifiedAt:String(r.last_verified_at)}:{}),...(r.last_error?{lastError:String(r.last_error)}:{})});
const run=(r:Record<string,unknown>):BackupRunView=>({id:String(r.id),targetId:String(r.target_id),status:String(r.status) as BackupRunView['status'],startedAt:String(r.started_at),completedAt:String(r.completed_at),...(r.file_path?{filePath:String(r.file_path)}:{}),...(r.size_bytes!=null?{sizeBytes:Number(r.size_bytes)}:{}),...(r.sha256?{sha256:String(r.sha256)}:{}),...(r.free_bytes!=null?{freeBytes:Number(r.free_bytes)}:{}),...(r.error?{error:String(r.error)}:{})});

export class SqliteBackupRepository extends SqliteRepository implements BackupRepositoryPort {
 listTargets(c:RepositoryExecutionContext):RepositoryResult<readonly BackupTargetView[]>{return this.execute(c,()=> (this.database(c).prepare('SELECT * FROM backup_targets ORDER BY created_at DESC').all() as Record<string,unknown>[]).map(target));}
 findTarget(c:RepositoryExecutionContext,id:string):RepositoryResult<BackupTargetView|undefined>{return this.execute(c,()=>{const r=this.database(c).prepare('SELECT * FROM backup_targets WHERE id=?').get(id) as Record<string,unknown>|undefined;return r?target(r):undefined;});}
 upsertTarget(c:RepositoryExecutionContext,t:BackupTargetView):RepositoryResult<void>{return this.execute(c,()=>{this.database(c).prepare('INSERT INTO backup_targets(id,name,kind,path,enabled,schedule,retention_count,retry_count,next_run_at,created_at) VALUES(?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,kind=excluded.kind,path=excluded.path,enabled=excluded.enabled,schedule=excluded.schedule,retention_count=excluded.retention_count,retry_count=excluded.retry_count,next_run_at=excluded.next_run_at').run(t.id,t.name,t.kind,t.path,t.enabled?1:0,t.schedule,t.retentionCount,t.retryCount,t.nextRunAt??null,t.createdAt);});}
 listRuns(c:RepositoryExecutionContext,limit:number):RepositoryResult<readonly BackupRunView[]>{return this.execute(c,()=> (this.database(c).prepare('SELECT * FROM backup_runs ORDER BY started_at DESC LIMIT ?').all(limit) as Record<string,unknown>[]).map(run));}
 listSuccessfulRuns(c:RepositoryExecutionContext,targetId:string):RepositoryResult<readonly BackupRunView[]>{return this.execute(c,()=> (this.database(c).prepare("SELECT * FROM backup_runs WHERE target_id=? AND status='success' ORDER BY completed_at DESC").all(targetId) as Record<string,unknown>[]).map(run));}
 listEnabledTargetIds(c:RepositoryExecutionContext):RepositoryResult<readonly string[]>{return this.execute(c,()=> (this.database(c).prepare('SELECT id FROM backup_targets WHERE enabled=1 ORDER BY created_at').all() as Array<{id:string}>).map(x=>x.id));}
 listDueTargetIds(c:RepositoryExecutionContext,at:string):RepositoryResult<readonly string[]>{return this.execute(c,()=> (this.database(c).prepare("SELECT id FROM backup_targets WHERE enabled=1 AND schedule<>'manual' AND next_run_at IS NOT NULL AND next_run_at<=? ORDER BY next_run_at").all(at) as Array<{id:string}>).map(x=>x.id));}
 insertRun(c:RepositoryExecutionContext,r:BackupRunView):RepositoryResult<void>{return this.execute(c,()=>{this.database(c).prepare('INSERT INTO backup_runs(id,target_id,status,file_path,size_bytes,sha256,free_bytes,error,started_at,completed_at) VALUES(?,?,?,?,?,?,?,?,?,?)').run(r.id,r.targetId,r.status,r.filePath??null,r.sizeBytes??null,r.sha256??null,r.freeBytes??null,r.error??null,r.startedAt,r.completedAt);});}
 markTargetSuccess(c:RepositoryExecutionContext,id:string,completedAt:string,nextRunAt?:string):RepositoryResult<void>{return this.execute(c,()=>{this.database(c).prepare('UPDATE backup_targets SET last_success_at=?,last_verified_at=?,last_error=NULL,next_run_at=? WHERE id=?').run(completedAt,completedAt,nextRunAt??null,id);});}
 markTargetFailure(c:RepositoryExecutionContext,id:string,error:string):RepositoryResult<void>{return this.execute(c,()=>{this.database(c).prepare('UPDATE backup_targets SET last_error=? WHERE id=?').run(error,id);});}
 deleteRun(c:RepositoryExecutionContext,id:string):RepositoryResult<void>{return this.execute(c,()=>{this.database(c).prepare('DELETE FROM backup_runs WHERE id=?').run(id);});}
}
