import type { DiagnosticRecord, DiagnosticRepositoryPort } from '@ppt/repository-contracts';
import { asIsoDateTime, type IsoDateTime } from '@ppt/core';
import type { DiagnosticArchiveView, DiagnosticEntryView, DiagnosticReportHistoryView, ExportArtifactView, HealthNotificationView, MaintenanceHistoryFilterInput, MaintenanceHistoryView, MaintenancePolicyView, PerformanceSampleView, SystemHealthHistoryView } from '@ppt/domain';
import type { RepositoryResult } from '@ppt/repository-contracts';
import { SqliteRepository } from './sqlite-base.js';
import type { RepositoryExecutionContext } from '@ppt/repository-contracts';
import { SensitiveLogPolicy } from '@ppt/platform-policy';

const sensitiveLogPolicy = new SensitiveLogPolicy();
const diagnostic=(r:Record<string,unknown>):DiagnosticEntryView=>{
  const value:DiagnosticEntryView={id:String(r.id),severity:String(r.severity) as DiagnosticEntryView['severity'],code:String(r.code),message:String(r.message),...(r.details?{details:String(r.details)}:{}),occurredAt:String(r.occurred_at)};
  if(!sensitiveLogPolicy.verifyDiagnostic(value)) throw new Error('SENSITIVE_LOG_STORED_DIAGNOSTIC_INVALID');
  return value;
};
const performance=(r:Record<string,unknown>):PerformanceSampleView=>({id:String(r.id),cpuLoadPercent:Number(r.cpu_load_percent),memoryUsagePercent:Number(r.memory_usage_percent),databaseBytes:Number(r.database_bytes),archiveBytes:Number(r.archive_bytes),sampledAt:String(r.sampled_at)});
const health=(r:Record<string,unknown>):SystemHealthHistoryView=>({id:String(r.id),score:Number(r.score),grade:String(r.grade) as SystemHealthHistoryView['grade'],systemStatus:String(r.system_status) as SystemHealthHistoryView['systemStatus'],deductions:Number(r.deductions),capturedAt:String(r.captured_at)});
const maintenance=(r:Record<string,unknown>):MaintenanceHistoryView=>({id:String(r.id),operation:String(r.operation) as MaintenanceHistoryView['operation'],success:Boolean(r.success),message:String(r.message),startedAt:String(r.started_at),completedAt:String(r.completed_at),durationMs:Number(r.duration_ms),source:String(r.source) as MaintenanceHistoryView['source']});

const policy=(r:Record<string,unknown>):MaintenancePolicyView=>({id:String(r.id),enabled:Boolean(r.enabled),intervalHours:Number(r.interval_hours),keepDiagnosticDays:Number(r.keep_diagnostic_days),keepPerformanceDays:Number(r.keep_performance_days),...(r.next_run_at?{nextRunAt:String(r.next_run_at)}:{}),...(r.last_run_at?{lastRunAt:String(r.last_run_at)}:{}),createdAt:String(r.created_at)});

const exportArtifact=(r:Record<string,unknown>):ExportArtifactView=>({id:String(r.id),kind:String(r.kind) as ExportArtifactView['kind'],format:String(r.format) as ExportArtifactView['format'],filePath:String(r.file_path),sha256:String(r.sha256),sizeBytes:Number(r.size_bytes),...(r.record_count===null||r.record_count===undefined?{}:{recordCount:Number(r.record_count)}),createdAt:String(r.created_at)});
const diagnosticReport=(r:Record<string,unknown>):DiagnosticReportHistoryView=>({id:String(r.id),generatedAt:String(r.generated_at),healthScore:Number(r.health_score),status:String(r.status) as DiagnosticReportHistoryView['status'],...(r.file_path?{filePath:String(r.file_path)}:{}),sha256:String(r.sha256),sizeBytes:Number(r.size_bytes)});
const diagnosticArchive=(r:Record<string,unknown>):DiagnosticArchiveView=>({id:String(r.id),createdAt:String(r.created_at),from:String(r.from_at),to:String(r.to_at),entryCount:Number(r.entry_count),filePath:String(r.file_path),sha256:String(r.sha256),sizeBytes:Number(r.size_bytes)});
const notification=(r:Record<string,unknown>):HealthNotificationView=>({id:String(r.id),severity:String(r.severity) as HealthNotificationView['severity'],code:String(r.code),title:String(r.title),message:String(r.message),createdAt:String(r.created_at),...(r.acknowledged_at?{acknowledgedAt:String(r.acknowledged_at)}:{}),...(r.generated_task_id?{generatedTaskId:String(r.generated_task_id)}:{})});

export class SqliteDiagnosticRepository extends SqliteRepository implements DiagnosticRepositoryPort {
  public insertIfAbsent(c:RepositoryExecutionContext,r:DiagnosticRecord):RepositoryResult<void>{return this.execute(c,()=>{const safe=sensitiveLogPolicy.sanitizeDiagnostic(r);this.database(c).prepare('INSERT OR IGNORE INTO diagnostic_entries(id,severity,code,message,details,occurred_at) VALUES(?,?,?,?,?,?)').run(safe.id,safe.severity,safe.code,safe.message,safe.details??null,safe.occurredAt);});}
  public insertDiagnostic(c:RepositoryExecutionContext,r:DiagnosticEntryView):RepositoryResult<void>{return this.execute(c,()=>{if(!sensitiveLogPolicy.verifyDiagnostic(r))throw new Error('SENSITIVE_LOG_DIAGNOSTIC_WRITE_REJECTED');this.database(c).prepare('INSERT INTO diagnostic_entries(id,severity,code,message,details,occurred_at) VALUES(?,?,?,?,?,?)').run(r.id,r.severity,r.code,r.message,r.details??null,r.occurredAt);});}
  public listDiagnostics(c:RepositoryExecutionContext,limit:number):RepositoryResult<readonly DiagnosticEntryView[]>{return this.execute(c,()=> (this.database(c).prepare('SELECT * FROM diagnostic_entries ORDER BY occurred_at DESC LIMIT ?').all(limit) as Record<string,unknown>[]).map(diagnostic));}
  public insertPerformanceSample(c:RepositoryExecutionContext,r:PerformanceSampleView):RepositoryResult<void>{return this.execute(c,()=>{this.database(c).prepare('INSERT INTO performance_samples(id,cpu_load_percent,memory_usage_percent,database_bytes,archive_bytes,sampled_at) VALUES(?,?,?,?,?,?)').run(r.id,r.cpuLoadPercent,r.memoryUsagePercent,r.databaseBytes,r.archiveBytes,r.sampledAt);});}
  public listPerformanceSamples(c:RepositoryExecutionContext,limit:number):RepositoryResult<readonly PerformanceSampleView[]>{return this.execute(c,()=> (this.database(c).prepare('SELECT * FROM performance_samples ORDER BY sampled_at DESC LIMIT ?').all(limit) as Record<string,unknown>[]).map(performance));}
  public listPerformanceSamplesSince(c:RepositoryExecutionContext,since:string):RepositoryResult<readonly PerformanceSampleView[]>{return this.execute(c,()=> (this.database(c).prepare('SELECT * FROM performance_samples WHERE sampled_at>=? ORDER BY sampled_at').all(since) as Record<string,unknown>[]).map(performance));}
  public insertSystemHealthHistory(c:RepositoryExecutionContext,r:SystemHealthHistoryView):RepositoryResult<void>{return this.execute(c,()=>{this.database(c).prepare('INSERT INTO system_health_history(id,score,grade,system_status,deductions,captured_at) VALUES(?,?,?,?,?,?)').run(r.id,r.score,r.grade,r.systemStatus,r.deductions,r.capturedAt);});}
  public listSystemHealthHistory(c:RepositoryExecutionContext,limit:number):RepositoryResult<readonly SystemHealthHistoryView[]>{return this.execute(c,()=> (this.database(c).prepare('SELECT * FROM system_health_history ORDER BY captured_at DESC LIMIT ?').all(limit) as Record<string,unknown>[]).map(health));}
  public listSystemHealthHistorySince(c:RepositoryExecutionContext,since:string):RepositoryResult<readonly SystemHealthHistoryView[]>{return this.execute(c,()=> (this.database(c).prepare('SELECT * FROM system_health_history WHERE captured_at>=? ORDER BY captured_at').all(since) as Record<string,unknown>[]).map(health));}
  public insertMaintenanceHistory(c:RepositoryExecutionContext,r:MaintenanceHistoryView):RepositoryResult<void>{return this.execute(c,()=>{this.database(c).prepare('INSERT INTO maintenance_history(id,operation,success,message,started_at,completed_at,duration_ms,source) VALUES(?,?,?,?,?,?,?,?)').run(r.id,r.operation,r.success?1:0,r.message,r.startedAt,r.completedAt,r.durationMs,r.source);});}
  public listMaintenanceHistory(c:RepositoryExecutionContext,limit:number):RepositoryResult<readonly MaintenanceHistoryView[]>{return this.execute(c,()=> (this.database(c).prepare('SELECT * FROM maintenance_history ORDER BY started_at DESC LIMIT ?').all(limit) as Record<string,unknown>[]).map(maintenance));}
  public searchMaintenanceHistory(c:RepositoryExecutionContext,input:MaintenanceHistoryFilterInput):RepositoryResult<readonly MaintenanceHistoryView[]>{return this.execute(c,()=>{const where:string[]=[];const args:Array<string|number>=[];if(input.operation){where.push('operation=?');args.push(input.operation);}if(input.success!==undefined){where.push('success=?');args.push(input.success?1:0);}if(input.source){where.push('source=?');args.push(input.source);}if(input.from){where.push('started_at>=?');args.push(input.from);}if(input.to){where.push('started_at<=?');args.push(input.to);}args.push(input.limit??250);const sql=`SELECT * FROM maintenance_history ${where.length?'WHERE '+where.join(' AND '):''} ORDER BY started_at DESC LIMIT ?`;return (this.database(c).prepare(sql).all(...args) as Record<string,unknown>[]).map(maintenance);});}

  public getMaintenancePolicy(c:RepositoryExecutionContext):RepositoryResult<MaintenancePolicyView>{return this.execute(c,()=>policy(this.database(c).prepare("SELECT * FROM maintenance_policy WHERE id='default'").get() as Record<string,unknown>));}
  public upsertMaintenancePolicy(c:RepositoryExecutionContext,p:MaintenancePolicyView):RepositoryResult<void>{return this.execute(c,()=>{this.database(c).prepare("UPDATE maintenance_policy SET enabled=?,interval_hours=?,keep_diagnostic_days=?,keep_performance_days=?,next_run_at=?,last_run_at=? WHERE id='default'").run(p.enabled?1:0,p.intervalHours,p.keepDiagnosticDays,p.keepPerformanceDays,p.nextRunAt??null,p.lastRunAt??null);});}
  public updateMaintenanceSchedule(c:RepositoryExecutionContext,lastRunAt:string,nextRunAt:string):RepositoryResult<void>{return this.execute(c,()=>{this.database(c).prepare("UPDATE maintenance_policy SET last_run_at=?,next_run_at=? WHERE id='default'").run(lastRunAt,nextRunAt);});}
  public countDiagnostics(c:RepositoryExecutionContext):RepositoryResult<number>{return this.execute(c,()=>Number((this.database(c).prepare('SELECT COUNT(*) c FROM diagnostic_entries').get() as {c:number}).c));}
  public countPerformanceSamples(c:RepositoryExecutionContext):RepositoryResult<number>{return this.execute(c,()=>Number((this.database(c).prepare('SELECT COUNT(*) c FROM performance_samples').get() as {c:number}).c));}
  public deleteDiagnosticsBefore(c:RepositoryExecutionContext,cutoff:string):RepositoryResult<void>{return this.execute(c,()=>{this.database(c).prepare('DELETE FROM diagnostic_entries WHERE occurred_at<?').run(cutoff);});}
  public deletePerformanceSamplesBefore(c:RepositoryExecutionContext,cutoff:string):RepositoryResult<void>{return this.execute(c,()=>{this.database(c).prepare('DELETE FROM performance_samples WHERE sampled_at<?').run(cutoff);});}
  public listHealthNotifications(c:RepositoryExecutionContext,limit:number):RepositoryResult<readonly HealthNotificationView[]>{return this.execute(c,()=> (this.database(c).prepare('SELECT * FROM health_notifications ORDER BY created_at DESC LIMIT ?').all(limit) as Record<string,unknown>[]).map(notification));}
  public findActiveHealthNotification(c:RepositoryExecutionContext,code:string):RepositoryResult<HealthNotificationView|undefined>{return this.execute(c,()=>{const r=this.database(c).prepare('SELECT * FROM health_notifications WHERE code=? AND acknowledged_at IS NULL ORDER BY created_at DESC LIMIT 1').get(code) as Record<string,unknown>|undefined;return r?notification(r):undefined;});}
  public insertHealthNotification(c:RepositoryExecutionContext,e:HealthNotificationView):RepositoryResult<void>{return this.execute(c,()=>{this.database(c).prepare('INSERT INTO health_notifications(id,severity,code,title,message,created_at,acknowledged_at,generated_task_id) VALUES(?,?,?,?,?,?,?,?)').run(e.id,e.severity,e.code,e.title,e.message,e.createdAt,e.acknowledgedAt??null,e.generatedTaskId??null);});}
  public attachHealthNotificationTask(c:RepositoryExecutionContext,id:string,taskId:string):RepositoryResult<void>{return this.execute(c,()=>{this.database(c).prepare('UPDATE health_notifications SET generated_task_id=? WHERE id=?').run(taskId,id);});}
  public acknowledgeHealthNotification(c:RepositoryExecutionContext,id:string,at:string):RepositoryResult<void>{return this.execute(c,()=>{this.database(c).prepare('UPDATE health_notifications SET acknowledged_at=? WHERE id=?').run(at,id);});}
  public countFailedBackupsSince(c:RepositoryExecutionContext,since:string):RepositoryResult<number>{return this.execute(c,()=>Number((this.database(c).prepare("SELECT COUNT(*) c FROM backup_runs WHERE status='failed' AND completed_at>=?").get(since) as {c:number}).c));}
  public countDiagnosticsByCodeSince(c:RepositoryExecutionContext,code:string,since:string):RepositoryResult<number>{return this.execute(c,()=>Number((this.database(c).prepare('SELECT COUNT(*) c FROM diagnostic_entries WHERE code=? AND occurred_at>=?').get(code,since) as {c:number}).c));}
  public countActiveHealthNotifications(c:RepositoryExecutionContext):RepositoryResult<number>{return this.execute(c,()=>Number((this.database(c).prepare('SELECT COUNT(*) c FROM health_notifications WHERE acknowledged_at IS NULL').get() as {c:number}).c));}
  public insertExportArtifact(c:RepositoryExecutionContext,e:ExportArtifactView):RepositoryResult<void>{return this.execute(c,()=>{this.database(c).prepare('INSERT INTO export_artifacts(id,kind,format,file_path,sha256,size_bytes,record_count,created_at) VALUES(?,?,?,?,?,?,?,?)').run(e.id,e.kind,e.format,e.filePath,e.sha256,e.sizeBytes,e.recordCount??null,e.createdAt);});}
  public listExportArtifacts(c:RepositoryExecutionContext,limit:number):RepositoryResult<readonly ExportArtifactView[]>{return this.execute(c,()=> (this.database(c).prepare('SELECT * FROM export_artifacts ORDER BY created_at DESC LIMIT ?').all(limit) as Record<string,unknown>[]).map(exportArtifact));}
  public findExportArtifact(c:RepositoryExecutionContext,id:string):RepositoryResult<ExportArtifactView|undefined>{return this.execute(c,()=>{const r=this.database(c).prepare('SELECT * FROM export_artifacts WHERE id=?').get(id) as Record<string,unknown>|undefined;return r?exportArtifact(r):undefined;});}
  public insertDiagnosticReport(c:RepositoryExecutionContext,e:DiagnosticReportHistoryView):RepositoryResult<void>{return this.execute(c,()=>{this.database(c).prepare('INSERT INTO diagnostic_reports(id,generated_at,health_score,status,file_path,sha256,size_bytes) VALUES(?,?,?,?,?,?,?)').run(e.id,e.generatedAt,e.healthScore,e.status,e.filePath??null,e.sha256,e.sizeBytes);});}
  public listDiagnosticReports(c:RepositoryExecutionContext,limit:number):RepositoryResult<readonly DiagnosticReportHistoryView[]>{return this.execute(c,()=> (this.database(c).prepare('SELECT * FROM diagnostic_reports ORDER BY generated_at DESC LIMIT ?').all(limit) as Record<string,unknown>[]).map(diagnosticReport));}
  public findDiagnosticReport(c:RepositoryExecutionContext,id:string):RepositoryResult<DiagnosticReportHistoryView|undefined>{return this.execute(c,()=>{const r=this.database(c).prepare('SELECT * FROM diagnostic_reports WHERE id=?').get(id) as Record<string,unknown>|undefined;return r?diagnosticReport(r):undefined;});}
  public insertDiagnosticArchive(c:RepositoryExecutionContext,e:DiagnosticArchiveView):RepositoryResult<void>{return this.execute(c,()=>{this.database(c).prepare('INSERT INTO diagnostic_archives(id,created_at,from_at,to_at,entry_count,file_path,sha256,size_bytes) VALUES(?,?,?,?,?,?,?,?)').run(e.id,e.createdAt,e.from,e.to,e.entryCount,e.filePath,e.sha256,e.sizeBytes);});}
  public listDiagnosticArchives(c:RepositoryExecutionContext,limit:number):RepositoryResult<readonly DiagnosticArchiveView[]>{return this.execute(c,()=> (this.database(c).prepare('SELECT * FROM diagnostic_archives ORDER BY created_at DESC LIMIT ?').all(limit) as Record<string,unknown>[]).map(diagnosticArchive));}
  public findDiagnosticArchive(c:RepositoryExecutionContext,id:string):RepositoryResult<DiagnosticArchiveView|undefined>{return this.execute(c,()=>{const r=this.database(c).prepare('SELECT * FROM diagnostic_archives WHERE id=?').get(id) as Record<string,unknown>|undefined;return r?diagnosticArchive(r):undefined;});}
  public deleteDiagnosticsThrough(c:RepositoryExecutionContext,cutoff:string):RepositoryResult<void>{return this.execute(c,()=>{this.database(c).prepare('DELETE FROM diagnostic_entries WHERE occurred_at<=?').run(cutoff);});}

}
