import type { LegacyPlanRow, LegacyRepositoryPort } from '@ppt/repository-contracts';
import { asIsoDateTime, type IsoDateTime, type UserId } from '@ppt/core';
import type { DigitalLegacyPlanView, LegacyApprovalView, LegacyGrantView } from '@ppt/domain';
import type { RepositoryResult } from '@ppt/repository-contracts';
import { SqliteRepository } from './sqlite-base.js';
import type { RepositoryExecutionContext } from '@ppt/repository-contracts';
const arr=(v:unknown):string[]=>{try{const x=JSON.parse(String(v));return Array.isArray(x)?x.filter((y):y is string=>typeof y==='string'):[]}catch{return[]}};
const plan=(x:Record<string,unknown>):LegacyPlanRow=>({id:String(x.id),ownerPersonId:String(x.owner_person_id),title:String(x.title),status:String(x.status) as DigitalLegacyPlanView['status'],triggerType:String(x.trigger_type) as DigitalLegacyPlanView['triggerType'],trusteeAccountId:String(x.trustee_account_id),...(x.secondary_trustee_account_id?{secondaryTrusteeAccountId:String(x.secondary_trustee_account_id)}:{}),...(x.instructions?{instructions:String(x.instructions)}:{}),startsAt:String(x.starts_at),waitingDays:Number(x.waiting_days??7),rollbackHours:Number(x.rollback_hours??24),...(x.execution_requested_at?{executionRequestedAt:String(x.execution_requested_at)}:{}),...(x.execute_after?{executeAfter:String(x.execute_after)}:{}),...(x.rollback_until?{rollbackUntil:String(x.rollback_until)}:{}),...(x.confirmation_note?{confirmationNote:String(x.confirmation_note)}:{}),createdAt:String(x.created_at),updatedAt:String(x.updated_at)});
const grant=(x:Record<string,unknown>):LegacyGrantView=>({id:String(x.id),planId:String(x.plan_id),resourceType:String(x.resource_type),resourceId:String(x.resource_id),actions:arr(x.actions) as LegacyGrantView['actions'],createdAt:String(x.created_at)});
const approval=(x:Record<string,unknown>):LegacyApprovalView=>({id:String(x.id),planId:String(x.plan_id),approverAccountId:String(x.approver_account_id),decision:String(x.decision) as LegacyApprovalView['decision'],...(x.note?{note:String(x.note)}:{}),createdAt:String(x.created_at)});

export class SqliteLegacyRepository extends SqliteRepository implements LegacyRepositoryPort {
 listPlans(c:RepositoryExecutionContext):RepositoryResult<readonly LegacyPlanRow[]>{return this.execute(c,()=> (this.database(c).prepare('SELECT * FROM digital_legacy_plans ORDER BY updated_at DESC').all() as Array<Record<string,unknown>>).map(plan));}
 findPlan(c:RepositoryExecutionContext,id:string):RepositoryResult<LegacyPlanRow|null>{return this.execute(c,()=>{const x=this.database(c).prepare('SELECT * FROM digital_legacy_plans WHERE id=?').get(id) as Record<string,unknown>|undefined;return x?plan(x):null});}
 upsertPlan(c:RepositoryExecutionContext,p:LegacyPlanRow):RepositoryResult<void>{return this.execute(c,()=>{this.database(c).prepare(`INSERT INTO digital_legacy_plans(id,owner_person_id,title,status,trigger_type,trustee_account_id,secondary_trustee_account_id,instructions,starts_at,waiting_days,rollback_hours,execution_requested_at,execute_after,rollback_until,confirmation_note,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET owner_person_id=excluded.owner_person_id,title=excluded.title,status=excluded.status,trigger_type=excluded.trigger_type,trustee_account_id=excluded.trustee_account_id,secondary_trustee_account_id=excluded.secondary_trustee_account_id,instructions=excluded.instructions,starts_at=excluded.starts_at,waiting_days=excluded.waiting_days,rollback_hours=excluded.rollback_hours,execution_requested_at=excluded.execution_requested_at,execute_after=excluded.execute_after,rollback_until=excluded.rollback_until,confirmation_note=excluded.confirmation_note,updated_at=excluded.updated_at`).run(p.id,p.ownerPersonId,p.title,p.status,p.triggerType,p.trusteeAccountId,p.secondaryTrusteeAccountId??null,p.instructions??null,p.startsAt,p.waitingDays,p.rollbackHours,p.executionRequestedAt??null,p.executeAfter??null,p.rollbackUntil??null,p.confirmationNote??null,p.createdAt,p.updatedAt);});}
 listGrants(c:RepositoryExecutionContext,planId?:string):RepositoryResult<readonly LegacyGrantView[]>{return this.execute(c,()=>((planId?this.database(c).prepare('SELECT * FROM legacy_grants WHERE plan_id=? ORDER BY created_at').all(planId):this.database(c).prepare('SELECT * FROM legacy_grants ORDER BY created_at').all()) as Array<Record<string,unknown>>).map(grant));}
 upsertGrant(c:RepositoryExecutionContext,g:LegacyGrantView):RepositoryResult<void>{return this.execute(c,()=>{this.database(c).prepare(`INSERT INTO legacy_grants(id,plan_id,resource_type,resource_id,actions,created_at) VALUES(?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET plan_id=excluded.plan_id,resource_type=excluded.resource_type,resource_id=excluded.resource_id,actions=excluded.actions`).run(g.id,g.planId,g.resourceType,g.resourceId,JSON.stringify(g.actions),g.createdAt);});}
 listApprovals(c:RepositoryExecutionContext,planId:string):RepositoryResult<readonly LegacyApprovalView[]>{return this.execute(c,()=> (this.database(c).prepare('SELECT * FROM legacy_approvals WHERE plan_id=? ORDER BY created_at').all(planId) as Array<Record<string,unknown>>).map(approval));}
 clearApprovals(c:RepositoryExecutionContext,planId:string):RepositoryResult<void>{return this.execute(c,()=>{this.database(c).prepare('DELETE FROM legacy_approvals WHERE plan_id=?').run(planId);});}
 upsertApproval(c:RepositoryExecutionContext,a:LegacyApprovalView):RepositoryResult<void>{return this.execute(c,()=>{this.database(c).prepare(`INSERT INTO legacy_approvals(id,plan_id,approver_account_id,decision,note,created_at) VALUES(?,?,?,?,?,?) ON CONFLICT(plan_id,approver_account_id) DO UPDATE SET decision=excluded.decision,note=excluded.note,created_at=excluded.created_at`).run(a.id,a.planId,a.approverAccountId,a.decision,a.note??null,a.createdAt);});}
 countApprovals(c:RepositoryExecutionContext,planId:string):RepositoryResult<number>{return this.execute(c,()=>Number((this.database(c).prepare("SELECT COUNT(DISTINCT approver_account_id) c FROM legacy_approvals WHERE plan_id=? AND decision='approved'").get(planId) as {c:number}).c));}
 replaceExecutionPermissions(c:RepositoryExecutionContext,planId:string,subject:UserId,grants:readonly LegacyGrantView[],at:IsoDateTime,ids:readonly string[]):RepositoryResult<void>{return this.execute(c,()=>{this.database(c).prepare('DELETE FROM object_permissions WHERE source_legacy_plan_id=?').run(planId);const q=this.database(c).prepare("INSERT INTO object_permissions(id,subject_account_id,resource_type,resource_id,actions,effect,starts_at,created_at,source_legacy_plan_id) VALUES(?,?,?,?,?,'allow',?,?,?)");grants.forEach((g,n)=>q.run(ids[n],subject,g.resourceType,g.resourceId,JSON.stringify(g.actions),at,at,planId));});}
 revokeExecutionPermissions(c:RepositoryExecutionContext,planId:string):RepositoryResult<void>{return this.execute(c,()=>{this.database(c).prepare('DELETE FROM object_permissions WHERE source_legacy_plan_id=?').run(planId);});}
}
