import type { TaskRepositoryPort } from '@ppt/repository-contracts';
import type { BackgroundTaskView, QueuedTaskView } from '@ppt/domain';
import type { RepositoryResult } from '@ppt/repository-contracts';
import { SqliteRepository } from './sqlite-base.js';
import type { RepositoryExecutionContext } from '@ppt/repository-contracts';
const bg=(r:Record<string,unknown>):BackgroundTaskView=>({id:String(r.id),taskType:String(r.task_type),label:String(r.label),status:String(r.status) as BackgroundTaskView['status'],startedAt:String(r.started_at),warningThresholdMs:Number(r.warning_threshold_ms),...(r.completed_at?{completedAt:String(r.completed_at)}:{}),...(r.duration_ms!=null?{durationMs:Number(r.duration_ms)}:{}),...(r.details?{details:String(r.details)}:{})});
const queued=(r:Record<string,unknown>):QueuedTaskView=>({id:String(r.id),taskType:String(r.task_type),label:String(r.label),priority:String(r.priority) as QueuedTaskView['priority'],status:String(r.status) as QueuedTaskView['status'],createdAt:String(r.created_at),attempts:Number(r.attempts),maxAttempts:Number(r.max_attempts),...(r.started_at?{startedAt:String(r.started_at)}:{}),...(r.completed_at?{completedAt:String(r.completed_at)}:{}),...(r.payload?{payload:String(r.payload)}:{}),...(r.details?{details:String(r.details)}:{})});

export class SqliteTaskRepository extends SqliteRepository implements TaskRepositoryPort {
 listBackgroundTasks(c:RepositoryExecutionContext,limit:number):RepositoryResult<readonly BackgroundTaskView[]>{return this.execute(c,()=> (this.database(c).prepare('SELECT * FROM background_tasks ORDER BY started_at DESC LIMIT ?').all(limit) as Record<string,unknown>[]).map(bg));}
 insertBackgroundTask(c:RepositoryExecutionContext,t:BackgroundTaskView):RepositoryResult<void>{return this.execute(c,()=>{this.database(c).prepare('INSERT INTO background_tasks(id,task_type,label,status,started_at,warning_threshold_ms) VALUES(?,?,?,?,?,?)').run(t.id,t.taskType,t.label,t.status,t.startedAt,t.warningThresholdMs);});}
 finishBackgroundTask(c:RepositoryExecutionContext,id:string,status:BackgroundTaskView['status'],completedAt:string,durationMs:number,details?:string):RepositoryResult<void>{return this.execute(c,()=>{this.database(c).prepare('UPDATE background_tasks SET status=?,completed_at=?,duration_ms=?,details=? WHERE id=?').run(status,completedAt,durationMs,details??null,id);});}
 listQueuedTasks(c:RepositoryExecutionContext,limit:number):RepositoryResult<readonly QueuedTaskView[]>{return this.execute(c,()=> (this.database(c).prepare("SELECT * FROM task_queue ORDER BY CASE priority WHEN 'critical' THEN 1 WHEN 'high' THEN 2 WHEN 'normal' THEN 3 ELSE 4 END, created_at LIMIT ?").all(limit) as Record<string,unknown>[]).map(queued));}
 listRunnableQueuedTasks(c:RepositoryExecutionContext,limit:number):RepositoryResult<readonly QueuedTaskView[]>{return this.execute(c,()=> (this.database(c).prepare("SELECT * FROM task_queue WHERE status IN ('queued','deferred') ORDER BY CASE priority WHEN 'critical' THEN 1 WHEN 'high' THEN 2 WHEN 'normal' THEN 3 ELSE 4 END, created_at LIMIT ?").all(limit) as Record<string,unknown>[]).map(queued));}
 enqueueTask(c:RepositoryExecutionContext,t:QueuedTaskView):RepositoryResult<void>{return this.execute(c,()=>{this.database(c).prepare('INSERT INTO task_queue(id,task_type,label,priority,status,created_at,attempts,max_attempts,payload) VALUES(?,?,?,?,?,?,?,?,?)').run(t.id,t.taskType,t.label,t.priority,t.status,t.createdAt,t.attempts,t.maxAttempts,t.payload??null);});}
 markQueuedTaskDeferred(c:RepositoryExecutionContext,id:string,details:string):RepositoryResult<void>{return this.execute(c,()=>{this.database(c).prepare("UPDATE task_queue SET status='deferred',details=? WHERE id=?").run(details,id);});}
 markQueuedTaskRunning(c:RepositoryExecutionContext,id:string,startedAt:string,attempts:number):RepositoryResult<void>{return this.execute(c,()=>{this.database(c).prepare("UPDATE task_queue SET status='running',started_at=?,attempts=? WHERE id=?").run(startedAt,attempts,id);});}
 markQueuedTaskCompleted(c:RepositoryExecutionContext,id:string,completedAt:string):RepositoryResult<void>{return this.execute(c,()=>{this.database(c).prepare("UPDATE task_queue SET status='completed',completed_at=?,details=NULL WHERE id=?").run(completedAt,id);});}
 markQueuedTaskRetryOrFailed(c:RepositoryExecutionContext,id:string,status:'queued'|'failed',completedAt:string|undefined,details:string):RepositoryResult<void>{return this.execute(c,()=>{this.database(c).prepare('UPDATE task_queue SET status=?,completed_at=?,details=? WHERE id=?').run(status,completedAt??null,details,id);});}
}
