import { Children,cloneElement,isValidElement,type ReactElement,type ReactNode } from 'react';
import type { SupportedUiLanguage } from '@ppt/domain';

const exactCopy:Readonly<Record<string,string>>={
  'Güvenli işlem bağlantısı kullanılamıyor.':'The secure operation connection is unavailable.','Geçiş anahtarları, bağlı hesaplar, süreli yetkiler ve eşlikçi cihaz kopyaları hazırlanıyor.':'Preparing passkeys, linked accounts, time-limited authorizations, and companion-device copies.',
  'Kimlik, geçiş anahtarı ve geçici yetki merkezi':'Identity, passkey, and temporary authorization center','Bu merkez yalnız bu bilgisayarda doğrulanan kimlik ve yetki kayıtlarını yönetir. Biyometrik veri veya geçiş anahtarının gizli anahtarı uygulamaya gelmez; resmî kimlik ya da hukuki yetki doğrulaması yapılmaz. Sağlayıcı kullanılabilirliği, uzaktaki iptal durumu ve ağ üzerinden teslim garanti edilmez.':'This center manages only identity and authorization records verified on this computer. Biometric data and passkey private keys never enter the app; it does not verify official identity or legal authority. Provider availability, remote revocation status, and network delivery are not guaranteed.','Gizli anahtar saklanmaz':'Private keys are not stored','Erişim anahtarı içeriği gösterilmez':'Access-key contents are not shown','Yazma işlemleri yalnız bu bilgisayarda yapılır':'Changes are made only on this computer',
  'Geçiş anahtarı ve cihaz doğrulaması':'Passkey and device verification','Geçiş anahtarı yalnız sizin onayınızla kullanılır. Uygulama biyometrik örnek istemez, yakalamaz veya saklamaz.':'A passkey is used only with your approval. The app never requests, captures, or stores biometric samples.','Geçiş anahtarı adı':'Passkey name','Cihaz onayı bekleniyor…':'Waiting for device approval…','Bu cihazda geçiş anahtarı oluştur':'Create a passkey on this device','Geçiş anahtarı yok':'No passkeys','Bu hesapta kayıtlı geçiş anahtarı bulunmuyor.':'No passkeys are registered for this account.','Kullanım sayısı':'Use count','cihaz doğrulama ayrıntısı saklanmaz':'device-verification details are not stored','Geçiş anahtarıyla doğrula':'Verify with passkey','Kayıp geçiş anahtarını kapatma':'Disable a lost passkey','Etkin geçiş anahtarı':'Active passkey','Geçiş anahtarı seçin':'Select a passkey','Bu işlem uzaktaki cihazı yönetmez veya silmez; yalnız bu bilgisayardaki geçiş anahtarı yetkisini ve eski oturumları kapatır.':'This action does not manage or erase a remote device; it only closes passkey authorization and older sessions on this computer.',
  'Bağlı hesaplar':'Linked accounts','Yalnız güvenilir biçimde yapılandırılmış hesap sağlayıcıları listelenir. Bağlantı, uygulamaya güvenli dönüş ve sağlayıcı imzası doğrulandıktan sonra etkin olur.':'Only securely configured account providers are listed. A connection becomes active after the secure return to the app and provider signature are verified.','Yapılandırılmış hesap sağlayıcısı yok':'No configured account providers','Yapılandırma bulundu · uygulamaya dönüşten sonra doğrulanacak':'Configuration found · verification follows the return to the app','Güvenli bağlantı açık':'Secure connection active','Güvenli bağlantıyı başlat':'Start secure connection','güvenli bağlantısı':'secure connection','dönüş doğrulaması şifreli kasada korunuyor':'return verification is protected in encrypted storage','Sağlayıcıdaki işlem tamamlanınca uygulamaya dönüş yalnız korumalı bölümde doğrulanır; geçici bağlantı bilgileri ekranda gösterilmez.':'After the provider step is completed, the return to the app is verified only in the protected area; temporary connection details are not shown.','Bağlı hesap yok':'No linked accounts','Erişim anahtarı içeriği ekranda veya yerel işlem kayıtlarında gösterilmez.':'Access-key contents are not shown on screen or in local activity records.','izin · erişim bilgileri şifreli kasada · teslim garantisi yok':'permissions · access details are stored in encrypted storage · delivery is not guaranteed',
  'Salt okunur eşlikçi cihaz kopyası':'Read-only companion-device copy','Bu bilgisayar ana kayıt yeridir. Eşlikçi cihaz yalnız şifreli, süreli ve salt okunur bir kopya alabilir; uzaktan değişiklik veya ağ üzerinden teslim yapılmaz.':'This computer is the primary record location. A companion device can receive only an encrypted, time-limited, read-only copy; remote changes and network delivery are unavailable.','Eşlikçi cihaz doğrulanmadı':'Companion device not verified','Şifreli kopya oluşturma, güvenilir bir cihaz anahtarı doğrulanana kadar kapalıdır.':'Encrypted-copy creation stays disabled until a trusted device key is verified.','Yazma isteğinin reddini denetle':'Check write-request rejection','Şifreli kopyayı kopyala':'Copy encrypted copy','Eşlikçi cihaz kopyası yok':'No companion-device copies','Hazırlanan kopyalar yalnız bu bilgisayarda listelenir; teslim edildiği iddia edilmez.':'Prepared copies are listed only on this computer; delivery is not claimed.','İşlem sürüyor; ikinci gönderim kilitli ve güvenli yeniden deneme bilgisi korunuyor.':'The action is in progress; a second submission is locked and secure retry information is preserved.','Kaynak sürümü':'Source version','belge düzeni':'document format','ağ üzerinden gönderilmedi':'not sent over the network','uzaktan değişiklik kabul edilmez':'remote changes are not accepted',
  'Kimlik ve yetki bridge’i kullanılamıyor.':'The identity and authorization bridge is unavailable.','Kimlik ve yetki merkezi yüklenemedi.':'The identity and authorization center could not be loaded.','Main-issued operation token bridge kullanılamıyor.':'The main-issued operation-token bridge is unavailable.','İşlem tamamlanamadı; yeniden deneme kimliği korundu.':'The operation could not be completed; the retry identity was preserved.','Kimlik ve geçici yetki merkezi yükleniyor':'Loading identity and temporary authorization center','Passkey, bağlı hesap, süreli belge ve companion metadata görünümü hazırlanıyor.':'Preparing the passkey, linked-account, time-limited credential, and companion metadata view.','Kimlik ve geçici yetki merkezi yüklenemedi':'The identity and temporary authorization center could not be loaded','Yetkili yerel görünüm kurulamadı.':'The authorized local view could not be established.','Kimlik ve geçici yetki merkezi boş':'The identity and temporary authorization center is empty','Bu hesap için yetkili yerel görünüm bulunamadı.':'No authorized local view was found for this account.',
  'Kimlik, passkey ve geçici yetki merkezi':'Identity, passkey, and temporary authorization center','Merkezi yenile':'Refresh center','Bu tek merkez yalnız yerel olarak doğrulanmış tören metadata’sını yönetir. Biyometrik veri veya passkey özel anahtarı uygulamaya gelmez; uzak attestation, resmi kimlik veya hukuk sertifikasyonu yapılmaz. Sağlayıcı kullanılabilirliği, uzak iptal güncelliği ve ağ teslimi garanti edilmez.':'This center manages only locally verified ceremony metadata. Biometric data and passkey private keys never enter the application; no remote attestation, official identity, or legal certification is performed. Provider availability, remote revocation freshness, and network delivery are not guaranteed.','Kimlik ve yetki sınırları':'Identity and authorization boundaries','Özel anahtar saklanmaz':'Private keys are not stored','Biyometrik veri saklanmaz':'Biometric data is not stored','Token baytları gösterilmez':'Token bytes are not displayed','Windows tek yazardır':'Windows is the sole writer','Henüz kimlik veya geçici yetki kaydı yok':'No identity or temporary authorization record yet','Aşağıdaki yerel, açık onaylı işlemlerden birini başlatabilirsiniz.':'You can start one of the explicit, locally approved operations below.',
  'Passkey ve cihaz doğrulaması':'Passkey and device verification','WebAuthn kullanıcı varlığı ve doğrulaması ister. Uygulama biyometrik örnek istemez, yakalamaz veya saklamaz.':'WebAuthn requires user presence and verification. The application never requests, captures, or stores biometric samples.','Passkey adı':'Passkey name','Bu cihazda passkey kaydet':'Register a passkey on this device','WebAuthn bekleniyor…':'Waiting for WebAuthn…','Passkey yok':'No passkeys','Bu hesapta kayıtlı passkey metadata’sı bulunmuyor.':'No registered passkey metadata exists for this account.','Etkin':'Active','İptal':'Revoked','Passkey ile doğrula':'Authenticate with passkey','İptal et':'Revoke','Kayıp passkey kurtarma':'Lost-passkey recovery','Etkin passkey':'Active passkey','Passkey seçin':'Select a passkey','Güçlü yerel yeniden doğrulama':'Strong local reauthentication','Hesap parolası fallback':'Account-password fallback','Hesap parolası':'Account password','İkinci faktör kodu':'Second-factor code','etkinse':'if enabled','Windows Hello ile doğrula ve yerel yetkiyi kapat':'Verify with Windows Hello and close local authority','Parola ile doğrula ve yerel yetkiyi kapat':'Verify with password and close local authority','Güçlü kanıtı main process üretir; kullanıcıdan kanıt kimliği alınmaz. Bu işlem uzak cihazı silmez, MDM çalıştırmaz; yalnız yerel credential yetkisini, güvenlik dönemini ve yerel oturumları kapatır.':'The main process creates the strong proof; no proof identifier is accepted from the user. This operation does not erase a remote device or invoke MDM; it closes only local credential authority, the security epoch, and local sessions.',
  'Federated kimlik bağları':'Federated identity links','Yalnız yapılandırılmış sağlayıcılar listelenir. Bağ ancak Authorization Code + PKCE, state, nonce, issuer, audience ve imza doğrulamasından sonra canlı kabul edilir.':'Only configured providers are listed. A link is considered live only after Authorization Code + PKCE, state, nonce, issuer, audience, and signature verification.','Yapılandırılmış sağlayıcı yok':'No configured provider','Apple, Google veya Microsoft için güvenilir tam yapılandırma bulunmadığından bağlantı başlatılamaz; sağlayıcı kullanılabilirliği iddia edilmez.':'No connection can start because no complete trusted Apple, Google, or Microsoft configuration exists; provider availability is not claimed.','Yapılandırma bulundu · canlı hesap kanıtı callback sonrası':'Configuration found · live-account proof follows callback','Yapılandırma bulundu · canlı hesap henüz doğrulanmadı':'Configuration found · live account not yet verified','Bağlı':'Linked','PKCE töreni açık':'PKCE ceremony active','PKCE bağlantısını başlat':'Start PKCE link','Sağlayıcı sayfasını aç':'Open provider page','Uygulamaya dönüşü doğrula ve bağla':'Verify app return and link','Bağlı federated kimlik yok':'No linked federated identity','Token baytları renderer’da veya yerel iş kayıtlarında gösterilmez.':'Token bytes are never displayed in the renderer or local operation records.','Canlı doğrulandı':'Verified live','Bağı kaldır':'Remove link',
  'Geçici doğrulanabilir yetkiler':'Temporary verifiable authorizations','Tür, amaç ve izinli alan matrisi sabittir. Yalnız zorunlu ve sizin doldurduğunuz isteğe bağlı alanlar imzalı QR payload’a girer. Bu payload resmi kimlik veya hukuki yetki sertifikası değildir.':'The type, purpose, and permitted-field matrix is fixed. Only required fields and optional fields you complete enter the signed QR payload. This payload is not an official identity or legal authorization certificate.','Yetki türü':'Authorization type','Amaç':'Purpose','Hedef kişi / bağlam':'Target person / context','Bitiş zamanı':'Expiry time','Minimum disclosure alanları':'Minimum-disclosure fields','zorunlu':'required','isteğe bağlı':'optional','Süreli, imzalı QR payload oluştur':'Create time-limited signed QR payload','QR payload hazır':'QR payload ready','Yalnız seçilen alanlar · özel imza anahtarı gösterilmez · ağ teslimi yapılmaz':'Only selected fields · private signing key is not displayed · no network delivery','QR payload’ı kopyala':'Copy QR payload','Çevrimdışı QR doğrulama':'Offline QR verification','QR payload':'QR payload','İmza ve süreyi çevrimdışı doğrula':'Verify signature and time offline','Geçici yetki yok':'No temporary authorization','Oluşturulan belgeler süre, amaç ve minimum disclosure metadata’sıyla burada görünür.':'Created credentials appear here with time, purpose, and minimum-disclosure metadata.','Yerel yetkiyi iptal et':'Revoke local authorization',
  'Salt okunur companion snapshot':'Read-only companion snapshot','Windows tek yazardır. Companion yalnız şifreli, süreli ve salt okunur snapshot alabilir; uzak yazma, çatışma birleştirme veya ağ teslimi yoktur.':'Windows is the sole writer. A companion can receive only an encrypted, time-limited, read-only snapshot; there is no remote writing, conflict merging, or network delivery.','Uygun güvenilir cihaz yok':'No eligible trusted device','Snapshot için aynı hesap ve güvenlik döneminde etkin bir güvenilir cihaz gerekir.':'A snapshot requires an active trusted device in the same account and security epoch.','Hedef güvenilir cihaz':'Target trusted device','bu cihaz':'this device','Bilinen kaynak sürümü':'Known source version','Şifreli salt okunur kopya oluştur':'Create encrypted read-only copy','Yazma reddini doğrula':'Verify write denial','Companion snapshot yok':'No companion snapshots','Üretilen metadata yalnız yerel merkezde listelenir; teslim sonucu iddia edilmez.':'Generated metadata is listed only in the local center; no delivery result is claimed.','İşlem sürüyor; ikinci gönderim kilitli ve retry kimliği korunuyor.':'Operation in progress; a second submission is locked and the retry identity is preserved.',
  'Bu cihazın passkey anahtarı':'This device passkey','Hedef kişi veya bağlam zorunludur.':'A target person or context is required.','Gelecekte bir bitiş zamanı seçin.':'Select a future expiry time.','zorunludur.':'is required.','Aynı işlem kimliği ve özgün revizyonla yeniden deneyebilirsiniz.':'You can retry with the same operation identity and original revision.','İşlem kimliği korundu':'The operation identity was preserved','yeniden deneme için korundu':'preserved for retry','ağ teslimi yok':'no network delivery','salt okunur':'read-only','bayt':'bytes','sayaç':'counter','güvenlik dönemi':'security epoch','saklanmaz':'not stored','Biyometri':'Biometrics','Son:':'Expires:','Bitiş yok':'No expiry'
};

const fragments=Object.entries(exactCopy).sort(([a],[b])=>b.length-a.length);
export const translateIdentityAccessCopy=(source:string,language:SupportedUiLanguage):string=>{
  if(language==='tr')return source;
  const value=source.trim(),exact=exactCopy[value];
  if(exact){const left=/^\s*/u.exec(source)?.[0]??'',right=/\s*$/u.exec(source)?.[0]??'';return`${left}${exact}${right}`;}
  let output=source;
  for(const[tr,en]of fragments){if(tr.length>=4&&output.includes(tr))output=output.split(tr).join(en);}
  return output;
};

const localizedProps=new Set(['aria-label','aria-description','title','description','body','message','eyebrow','placeholder','alt','label']);
export const localizeIdentityAccessNode=(node:ReactNode,language:SupportedUiLanguage):ReactNode=>{
  if(language==='tr'||node===null||node===undefined||typeof node==='boolean'||typeof node==='number')return node;
  if(typeof node==='string')return translateIdentityAccessCopy(node,language);
  if(Array.isArray(node))return Children.map(node,item=>localizeIdentityAccessNode(item,language));
  if(!isValidElement(node))return node;
  const element=node as ReactElement<Record<string,unknown>>,props:Record<string,unknown>={};
  if(element.props['data-localization-preserve']===true)return element;
  for(const key of localizedProps){const value=element.props[key];if(typeof value==='string')props[key]=translateIdentityAccessCopy(value,language);}
  if('actions'in element.props)props.actions=localizeIdentityAccessNode(element.props.actions as ReactNode,language);
  if('children'in element.props)props.children=localizeIdentityAccessNode(element.props.children as ReactNode,language);
  return cloneElement(element,props);
};
