import { Children, cloneElement, isValidElement, type ReactElement, type ReactNode } from 'react';
import type { SupportedUiLanguage } from '@ppt/domain';

const exactCopy: Readonly<Record<string,string>> = {
  '2FA kodu (etkinse)':'2FA code (when enabled)',
  '24 saat içinde sona erecek':'Expires within 24 hours',
  'Açık uçlu':'Open-ended',
  'Adres ve TLS pinleri güçlü doğrulamayla sağlayıcı köküne bağlanır; geçiş pini yalnız sınırlı zaman penceresinde kabul edilir.':'The address and TLS pins are bound to the provider root through strong verification; a transition pin is accepted only during a limited time window.',
  'Aile sağlık geçmişi':'Family health history',
  'Anahtar döndürme geçmişi':'Key-rotation history',
  'Anahtar parmak izi kanıt referansı':'Key-fingerprint evidence reference',
  'Anahtarı döndür':'Rotate key',
  'Ardıl anahtarlar önceki güvenilen Ed25519 anahtarının imzasıyla yetkilendirildiğinde burada görünür.':'Successor keys appear here when authorized by the previous trusted Ed25519 key signature.',
  'Ardıl anahtara devredildi':'Transferred to successor key',
  'Ardıl parmak izi:':'Successor fingerprint:',
  'Arşivle':'Archive',
  'Arşivlendi':'Archived',
  'Ayrı telefon görüşmesi, imzalı yazı veya bağımsız güven kanalı':'Separate phone call, signed letter, or independent trust channel',
  'Bağımsız kanaldan alınan SHA-256 parmak izi':'SHA-256 fingerprint obtained through an independent channel',
  'Bağımsız tanık adı':'Independent witness name',
  'Başarılı':'Successful',
  'Başarısız':'Failed',
  'Başlangıç zamanı bekleniyor':'Waiting for start time',
  'Bekletme etkin:':'Hold active:',
  'Bekletmeye al':'Place on hold',
  'Bekletmeyi kaldır':'Remove hold',
  'Birincil pin:':'Primary pin:',
  'Bulut sürüm geçmişi':'Cloud version history',
  'Bulut veya imha hizmeti':'Cloud or destruction service',
  'Çevrimdışı disk':'Offline disk',
  'Canlı kayıt kalıcı olarak imha edildi. Önceki yedek kopyalarının süre dolana kadar bulunabileceğini unutmayın.':'The live record was permanently destroyed. Remember that earlier backup copies may remain until their retention period expires.',
  'Devre dışı':'Disabled',
  'Diğer':'Other',
  'Doğrulama makbuzu SHA-256:':'Verification receipt SHA-256:',
  'Doğrulanmış imha makbuzları':'Verified destruction receipts',
  'Doğrulanmış kök güveni ekle':'Add verified root trust',
  'Doğrulanmış liste yok':'No verified list',
  'Doğrulanmış sağlayıcı imzası yok':'No verified provider signature',
  'doğrulandı':'verified',
  'Döndürme kaydı yok':'No rotation record',
  'Düzenle':'Edit',
  'Ed25519 PUBLIC KEY PEM':'Ed25519 PUBLIC KEY PEM',
  'Erişilemiyor':'Unreachable',
  'Eski kayıt; kurum dışı doğrulama makbuzu yok':'Legacy record; no out-of-band verification receipt',
  'Etkin':'Active',
  'etkin hedef':'active target',
  'Ev harici diski':'Home external drive',
  'Envanter güncel':'Inventory is current',
  'Finans kaydı':'Finance record',
  'Gecikmiş teyit':'Overdue review',
  'Geçerlilik:':'Validity:',
  'Geri al':'Restore',
  'Geri alma penceresi sonu:':'End of recovery window:',
  'Geri alma süresi (gün)':'Recovery period (days)',
  'Gerekçe kayıtlı':'Reason recorded',
  'Güven durumu:':'Trust status:',
  'Güveni iptal et':'Revoke trust',
  'Güvenilen kanıt sağlayıcısı':'Trusted evidence provider',
  'Güvenilen sağlayıcı yok':'No trusted provider',
  'Güvenilen sağlayıcının sabit kanonik biçimde imzaladığı makbuzlar burada görünür.':'Receipts signed by a trusted provider in the fixed canonical format appear here.',
  'Güvenli al ve uygula':'Securely fetch and apply',
  'Güçlü doğrulama parolası':'Strong-verification password',
  'Güncel':'Current',
  'Haricî disk':'External disk',
  'Hata:':'Error:',
  'Hazır':'Ready',
  'Henüz çalıştırılmadı':'Not run yet',
  'HTTPS kaynak profili yok':'No HTTPS source profile',
  'İki bağımsız kurum dışı kanıt':'Two independent out-of-band evidence sources',
  'İmha işlemi devam ettirilmeli':'Destruction must be resumed',
  'İmha talebi':'Request destruction',
  'İmha uygunluk tarihi:':'Destruction eligibility date:',
  'İmza doğrulandı':'Signature verified',
  'İlaç planı':'Medication plan',
  'İmzalı anahtar döndürmeden miras':'Inherited from signed key rotation',
  'İmzalı iptal listeleri':'Signed revocation lists',
  'İmzalı iptal listesini ağdan almak için kök sağlayıcıya bağlı adres ve SPKI pini kaydedin.':'Record an address and SPKI pin bound to the root provider to fetch the signed revocation list from the network.',
  'İmzalı kanıt doğrula':'Verify signed evidence',
  'İmzalı kanıt doğrulandı':'Signed evidence verified',
  'İmzalı kanıtın sağlayıcı güveni iptal edildi':'The provider trust for the signed evidence was revoked',
  'İmzalı makbuz doğrulamak için sağlayıcının Ed25519 açık anahtarını ekleyin.':'Add the provider Ed25519 public key to verify signed receipts.',
  'İmzalı makbuz yok':'No signed receipt',
  'İnceleme gerekli':'Review required',
  'İptal edildi':'Revoked',
  'İptal gerekçesi:':'Revocation reason:',
  'İptal listesi uygula':'Apply revocation list',
  'İptal listesi yok':'No revocation list',
  'Kalıcı çalışma geçmişi':'Durable run history',
  'Kalıcı durum':'Durable state',
  'Kalıcı imha':'Permanent destruction',
  'Kalıcı imha edildi':'Permanently destroyed',
  'Kalıcı imha öncesi tarihsel veri içerme riski var':'May contain historical data predating permanent destruction',
  'Karantina politikasını güncelle':'Update quarantine policy',
  'Karantina:':'Quarantined:',
  'Kanıt SHA-256:':'Evidence SHA-256:',
  'Kayıt etkin duruma geri alındı.':'The record was restored to active state.',
  'Kayıt geri alınabilir biçimde arşivlendi.':'The record was archived in a recoverable form.',
  'Kayıt imhaya karşı bekletmeye alındı.':'The record was placed on hold against destruction.',
  'Kayıt türleri':'Record types',
  'Kayıtlı kopya':'registered copy',
  'Kaynak profili ekle':'Add source profile',
  'Konum açıklaması':'Location description',
  'Kopya':'Copy',
  'Kopya adı':'Copy name',
  'Kopyayı envantere ekle':'Add copy to inventory',
  'Kök doğrulama:':'Root verification:',
  'Kök Ed25519 anahtarı ancak iki bağımsız kurum dışı kanıt, eşleşen SHA-256 parmak izi ve tanık kaydıyla eklenir.':'A root Ed25519 key is added only with two independent out-of-band evidence sources, a matching SHA-256 fingerprint, and a witness record.',
  'Kullanıcı beyanı ile sağlayıcı imzalı makbuz ayrı güven seviyeleridir. Geçerli imza yalnız güvenilen açık anahtar, kopya kimliği, makbuz kimliği, zaman ve SHA-256 değerinin değiştirilmediğini kanıtlar; fiziksel medyanın mutlak yok oluşunu tek başına garanti etmez.':'A user attestation and a provider-signed receipt represent different trust levels. A valid signature proves only that the trusted public key, copy ID, receipt ID, time, and SHA-256 value were not altered; it does not by itself guarantee the absolute physical destruction of the medium.',
  'Kullanıcı imha teyidi':'User destruction attestation',
  'Kurum kimliği kanıt referansı':'Legal-entity identity evidence reference',
  'Liste güncel':'List is current',
  'Manuel dosya':'Manual file',
  'Manuel dosyalar, çevrimdışı diskler ve bulut sürüm geçmişleri otomatik olarak silinmiş sayılmaz.':'Manual files, offline disks, and cloud version histories are not considered automatically deleted.',
  'Nihai imha':'Final destruction',
  'Nihai imha edildi':'Finally destroyed',
  'Operasyonel varsayılan süre hukuki saklama süresi değildir. Süre değişikliği yalnız yeni karantinalara uygulanır.':'The operational default period is not a legal retention period. A period change applies only to newly created quarantines.',
  'Otomatik politika etkin':'Automatic policy enabled',
  'Otomatik temiz yedek yeniden yazımı':'Automatic clean-backup rewrite',
  'Otomatik politika yalnız zamanlanmış çevrimi kontrol eder; “Şimdi çalıştır” manuel komutu politika kapalıyken de kullanılabilir. Manuel hata sonrası 1 saat, otomatik hata sonrası 6 saat geri çekilme uygulanır; yüksek sistem yükünde işlem güvenli biçimde ertelenir.':'The automatic policy controls only scheduled cycles; the “Run now” command remains available while the policy is disabled. A one-hour backoff follows a manual failure and a six-hour backoff follows an automatic failure; high system load safely postpones the operation.',
  'Önceki anahtar:':'Previous key:',
  'Parmak izi:':'Fingerprint:',
  'Payload SHA-256:':'Payload SHA-256:',
  'Politika adı':'Policy name',
  'Politika oluştur':'Create policy',
  'Politikayı kaydet':'Save policy',
  'Resmî tüzel kişi adı':'Official legal-entity name',
  'Sağlayıcı etiketi':'Provider label',
  'Sağlayıcı güven zinciri':'Provider trust chain',
  'Sağlayıcı güveni iptal edildi':'Provider trust revoked',
  'Sağlayıcı HTTPS kaynakları':'Provider HTTPS sources',
  'Sağlayıcı tarafından Ed25519 ile imzalanmış anahtar durum listeleri burada görünür.':'Key-status lists signed by the provider with Ed25519 appear here.',
  'Saklama politikası oluşturuldu.':'Retention policy created.',
  'Saklama sonu:':'Retention ends:',
  'Saklama süresi (gün)':'Retention period (days)',
  'Saklanıyor':'Retained',
  'Sağlık kaydı':'Health record',
  'Son alım:':'Last fetch:',
  'Son kullanıcı teyidi:':'Latest user attestation:',
  'Son tanı:':'Latest diagnostic:',
  'Son yayılım:':'Latest propagation:',
  'Sonraki teyit:':'Next review:',
  'Sonraki deneme':'next attempt',
  'Sorumlu kişi veya birim':'Responsible person or unit',
  'Sorumlu:':'Custodian:',
  'Sıra numarası geri alınamaz; süresi dolmuş liste güven durumunu yükseltemez.':'The sequence number cannot be rolled back; an expired list cannot raise trust status.',
  'Süresi dolan kayıt':'expired record',
  'Süresi doldu':'Expired',
  'SQLite güvenli silme ve WAL temizliği en iyi çaba yaklaşımıdır. SSD, dosya sistemi, bulut eşitlemesi ve yedekler fiziksel kopyaları bir süre tutabilir.':'SQLite secure deletion and WAL cleanup are best-effort. SSDs, file systems, cloud synchronization, and backups may retain physical copies for some time.',
  'Şimdi çalıştır':'Run now',
  'Talebi iptal et':'Cancel request',
  'Tanık kurumu/rolü':'Witness organization/role',
  'Tarihsel veri riski':'historical-data risk',
  'Temiz yedek çalışma geçmişi yok':'No clean-backup run history',
  'Teyit aralığı (gün)':'Review interval (days)',
  'Teyit et':'Review',
  'Ticaret sicili, imzalı sözleşme veya resmî rehber kaydı':'Trade registry, signed contract, or official directory record',
  'Tür':'Type',
  'Uygulama dışı kopya kaydı yok':'No external-copy record',
  'Uygulama dışı yedek envanteri':'External-backup inventory',
  'Uyarı: Önceki yedeklerde kopya bulunabilir.':'Warning: Earlier backups may contain a copy.',
  'Varsayılan işlem geri alınabilir arşivlemedir. Kalıcı imha ancak saklama süresi ve geri alma penceresi tamamlandıktan sonra güçlü doğrulamayla çalışır.':'The default action is recoverable archiving. Permanent destruction runs with strong verification only after the retention period and recovery window have ended.',
  'Veri saklama ve güvenli silme':'Data retention and secure deletion',
  'Yaşam kaydı':'Life record',
  'Yedek karantina saklama süresi (gün)':'Backup-quarantine retention period (days)',
  'Yedek karantinası bulunmuyor':'No backup quarantine',
  'Yönetilebilir kayıt bulunamadı':'No manageable record found',
  'Yönetilen eski yedekler karantinaya taşındığında burada görünür.':'Managed old backups appear here when moved to quarantine.',
  'Yönetilen yedeklerde imha yayılımı, saklama süresi dolmuş kayıtlar için önce doğrulanmış temiz yedek oluşturur; eski kopyayı geri alınabilir karantinaya taşır. Kayıtlı hedefler dışındaki manuel veya yönetilmeyen kopyalara dokunulmaz.':'For records whose retention period has ended, destruction propagation in managed backups first creates a verified clean backup and moves the old copy to recoverable quarantine. Manual or unmanaged copies outside registered targets are not touched.',
  'Yerine yeni liste geldi':'Superseded',
  '64 onaltılık karakter':'64 hexadecimal characters',
  'D: harici disk / kilitli dolap':'D: external disk / locked cabinet',
  'Finans, sağlık veya yaşam kaydı oluşturulduğunda yaşam döngüsü burada görünür.':'The lifecycle appears here when a finance, health, or life record is created.',
  'Her sahiplenilmiş deneme, SQLite üzerinde başlangıç ve atomik final durumuyla saklanır.':'Every claimed attempt is stored in SQLite with its initial and atomic final state.',
  'İlk sahiplenilmiş deneme başladığında kalıcı çalışma kaydı burada gösterilir.':'The durable run record appears here when the first claimed attempt starts.',
  'Manuel yedek, çevrimdışı disk ve bulut geçmişlerini burada kayıt altına alın.':'Record manual backups, offline disks, and cloud histories here.',
  'durum yazma hatası':'state write failed','geçiş':'transition','manuel':'manual','otomatik':'automatic',
  'Kayıt bekletmesi kaldırıldı.':'The record hold was removed.',
  'Kalıcı imha talebi iptal edildi.':'The permanent-destruction request was cancelled.',
  'Kalıcı imha talebi oluşturuldu; geri alma süresi boyunca iptal edilebilir.':'A permanent-destruction request was created; it can be cancelled during the recovery period.',
  'Kopya bekletmesi kaldırıldı.':'The copy hold was removed.','Kopya teyidi kaydedilemedi.':'The copy review could not be recorded.',
  'Saklama politikası oluşturulamadı.':'The retention policy could not be created.',
  'Sağlayıcı güveni iptal edilemedi.':'Provider trust could not be revoked.',
  'Temiz yedek yeniden yazımı tamamlanamadı.':'The clean-backup rewrite could not be completed.',
  'Temiz yedek yeniden yazım politikası güncellenemedi.':'The clean-backup rewrite policy could not be updated.',
  'Uygulama dışı yedek kaydı oluşturulamadı.':'The external-backup record could not be created.',
  'Veri yaşam döngüsü işlemi tamamlanamadı.':'The data-lifecycle operation could not be completed.',
  'Yedek karantina politikası güncellenemedi.':'The backup-quarantine policy could not be updated.',
  'Yedek karantina bekletmesi güncellenemedi.':'The backup-quarantine hold could not be updated.',
  'Yedek karantinası imha edilemedi.':'The backup quarantine could not be destroyed.','Yeniden yazılıyor…':'Rewriting…'
};

export const translateDataLifecycleCopy=(source:string,language:SupportedUiLanguage):string=>{
  if(language==='tr')return source;
  const value=source.trim();const translated=exactCopy[value];
  if(!translated){
    const cleanRewrite=/^Temiz yedek yeniden yazımı tamamlandı; (\d+) eski yedek karantinaya alındı\.$/u.exec(value);
    if(cleanRewrite)return `Clean-backup rewrite completed; ${cleanRewrite[1]} old backup(s) were quarantined.`;
    const quarantineDestroy=/^(\d+) karantina yedeği nihai imha edildi( ve yarım kalan işlem güvenli biçimde tamamlandı)?\.$/u.exec(value);
    if(quarantineDestroy)return `${quarantineDestroy[1]} quarantined backup(s) were finally destroyed${quarantineDestroy[2]?' and the interrupted operation was safely completed':''}.`;
    const appliedBytes=/^Ana süreçte bekletilen iptal listesi güçlü doğrulama ve Ed25519 imza denetimiyle uygulandı\. (\d+) bayt\.$/u.exec(value);
    if(appliedBytes)return `The revocation list held in the main process was applied with strong verification and Ed25519 signature validation. ${appliedBytes[1]} bytes.`;
    return source;
  }
  const leading=/^\s*/u.exec(source)?.[0]??'';const trailing=/\s*$/u.exec(source)?.[0]??'';
  return `${leading}${translated}${trailing}`;
};

const propsToTranslate=new Set(['aria-label','aria-description','title','description','body','message','eyebrow','placeholder','alt','label']);
export const localizeDataLifecycleNode=(node:ReactNode,language:SupportedUiLanguage):ReactNode=>{
  if(language==='tr'||node===null||node===undefined||typeof node==='boolean'||typeof node==='number')return node;
  if(typeof node==='string')return translateDataLifecycleCopy(node,language);
  if(Array.isArray(node))return Children.map(node,item=>localizeDataLifecycleNode(item,language));
  if(!isValidElement(node))return node;
  const element=node as ReactElement<Record<string,unknown>>;const props:Record<string,unknown>={};
  if(element.props['data-localization-preserve']===true)return element;
  for(const key of propsToTranslate){const value=element.props[key];if(typeof value==='string')props[key]=translateDataLifecycleCopy(value,language);}
  if('actions' in element.props)props.actions=localizeDataLifecycleNode(element.props.actions as ReactNode,language);
  if('children' in element.props)props.children=localizeDataLifecycleNode(element.props.children as ReactNode,language);
  return cloneElement(element,props);
};
