import { Children, cloneElement, isValidElement, type ReactElement, type ReactNode } from 'react';
import type { SupportedUiLanguage } from '@ppt/domain';

const exactCopy:Readonly<Record<string,string>>={
  'Yüksek gizlilik':'Highly private','Sağlık merkezi':'Health center','Sağlık olayları, ilaç/tedavi planları ve aile sağlık geçmişi tek izin modeli altında tutulur.':'Health events, medication/treatment plans, and family health history are kept under one permission model.','Yeni sağlık kaydı':'New health record','Kayıt sahibi':'Record owner','Başlık':'Title','Tür':'Type','Randevu':'Appointment','İlaç':'Medication','Tanı':'Diagnosis','Aşı':'Vaccine','Not':'Note','Hekim/Kurum':'Clinician/Organization','Gizlilik':'Privacy','Özel':'Private','Seçili üyeler':'Selected members','Aile':'Family','Kaydet':'Save','İlaç / tedavi planı':'Medication / treatment plan','İlaç veya tedavi':'Medication or treatment','Doz':'Dose','Kullanım planı':'Usage schedule','Planı ekle':'Add plan','Aile sağlık geçmişi':'Family health history','Rahatsızlık / durum':'Condition / status','Geçmişe ekle':'Add to history','Görüntüleyebildiğiniz sağlık verileri':'Health data you are allowed to view','kayıt':'records','plan':'plans','geçmiş':'history','Sağlık kaydı eklendi.':'Health record added.','Kayıt eklenemedi.':'The record could not be added.','İlaç/tedavi planı eklendi.':'Medication/treatment plan added.','Plan eklenemedi.':'The plan could not be added.','Aile sağlık geçmişi eklendi.':'Family health history added.','Geçmiş eklenemedi.':'The history entry could not be added.',
  'Aile operasyon merkezi':'Family operations center','Yaşam merkezi':'Life center','Görev, sigorta, eğitim, iş geçmişi, ev–araç varlıkları ve acil durum planlarını tek güvenli kayıt modelinde yönetin.':'Manage tasks, insurance, education, employment history, home and vehicle assets, and emergency plans in one secure record model.','Yeni yaşam kaydı':'New life record','Kategori':'Category','Durum':'Status','Planlandı':'Planned','Aktif':'Active','Tamamlandı':'Completed','Süresi doldu':'Expired','İptal':'Cancelled','Vade / tarih':'Due date / date','Kurum / sağlayıcı':'Organization / provider','Tutar':'Amount','Erişebildiğiniz kayıtlar':'Records you can access','yaşam kaydı':'life records','Görev':'Task','Sigorta':'Insurance','Eğitim':'Education','Abonelik':'Subscription','Resmî işlem':'Official process','İş geçmişi':'Employment history','Ev / araç':'Home / vehicle','Acil durum':'Emergency','Yaşam kaydı eklendi.':'Life record added.',
  'Akıllı takip':'Smart tracking','Bildirim ve otomasyon merkezi':'Notification and automation center','Önemli gün, görev, finans ve ilaç planları için yerel hatırlatma kuralları oluşturun.':'Create local reminder rules for important days, tasks, finance, and medication plans.','Kuralları şimdi çalıştır':'Run rules now','Yeni kural':'New rule','Otomasyon oluştur':'Create automation','Yaklaşan görev hatırlatması':'Upcoming task reminder','Kaynak':'Source','Önemli gün':'Important day','Yaşam kaydı':'Life record','Finans kaydı':'Finance record','İlaç planı':'Medication plan','Kaç gün önce':'Days before','gün önce':'days before','Kural ekle':'Add rule','Kurallar':'Rules','otomasyon':'automations','Etkin':'Enabled','Kapalı':'Disabled','Kapat':'Disable','Etkinleştir':'Enable','Kural yok':'No rules','İlk otomasyon kuralınızı oluşturun.':'Create your first automation rule.','Çalışma geçmişi':'Run history','sonuç':'results','Görev üretildi':'Task generated','Atlandı':'Skipped','Başarısız':'Failed','Henüz çalışma yok':'No runs yet','Kuralları şimdi çalıştırdığınızda sonuçlar burada görünür':'Results appear here when you run the rules.','Etkin kurallar şimdi değerlendirildi.':'Enabled rules were evaluated.','Kurallar çalıştırılamadı.':'Rules could not be run.','Otomasyon kuralı eklendi.':'Automation rule added.','Kural eklenemedi.':'The rule could not be added.',
  'Rapor hazırlanıyor…':'Preparing report…','Aile görünümü':'Family view','Raporlama merkezi':'Reporting center','Son üretim:':'Last generated:','PDF raporu oluştur':'Create PDF report','Operasyon':'Operations','Aile özeti':'Family summary','Aktif aile üyesi':'Active family members','30 gün içindeki etkinlik':'Events within 30 days','Aktif görev':'Active tasks','30 gün içinde bitecek sigorta':'Insurance expiring within 30 days','Aktif ilaç planı':'Active medication plans','Finans ve gecikmeler':'Finance and overdue items','Özet':'Summary','Varlık':'Assets','Borç':'Debt','Gecikmiş':'Overdue','Gecikmiş kayıt yok':'No overdue records','Takip edilen tüm kayıtlar güncel görünüyor.':'All tracked records appear current.','PDF raporu kaydedildi:':'PDF report saved:'
};
const fragments=Object.entries(exactCopy).sort(([left],[right])=>right.length-left.length);
export const translateOperationsCenterCopy=(source:string,language:SupportedUiLanguage):string=>{
  if(language==='tr')return source;const value=source.trim();const translated=exactCopy[value];
  if(translated){const leading=/^\s*/u.exec(source)?.[0]??'';const trailing=/\s*$/u.exec(source)?.[0]??'';return `${leading}${translated}${trailing}`;}
  let localized=source;for(const [turkish,english] of fragments){if(turkish.length>=4&&localized.includes(turkish))localized=localized.split(turkish).join(english);}return localized;
};
const propsToTranslate=new Set(['aria-label','aria-description','title','description','body','message','eyebrow','placeholder','alt','label']);
export const localizeOperationsCenterNode=(node:ReactNode,language:SupportedUiLanguage):ReactNode=>{
  if(language==='tr'||node===null||node===undefined||typeof node==='boolean'||typeof node==='number')return node;
  if(typeof node==='string')return translateOperationsCenterCopy(node,language);
  if(Array.isArray(node))return Children.map(node,item=>localizeOperationsCenterNode(item,language));if(!isValidElement(node))return node;
  const element=node as ReactElement<Record<string,unknown>>;const props:Record<string,unknown>={};if(element.props['data-localization-preserve']===true)return element;
  for(const key of propsToTranslate){const value=element.props[key];if(typeof value==='string')props[key]=translateOperationsCenterCopy(value,language);}
  if('actions' in element.props)props.actions=localizeOperationsCenterNode(element.props.actions as ReactNode,language);if('action' in element.props)props.action=localizeOperationsCenterNode(element.props.action as ReactNode,language);if('children' in element.props)props.children=localizeOperationsCenterNode(element.props.children as ReactNode,language);return cloneElement(element,props);
};
