/* eslint-disable */
// This file is generated by scripts/generate-ppk026-policy-client.mjs.
// Manual edits are rejected by the PPK-026 deterministic code-generation gate.
import type {
  CoreServiceMethodPayload,
  CoreServiceMethodResult,
  PolicyAuthorizationContractPayload,
  PolicyAuthorizationContractResult,
  PolicyReceiptVerificationContractPayload,
  PolicyReceiptVerificationContractResult
} from '@ppt/core-service-contracts';

export const GENERATED_POLICY_CLIENT_SCHEMA_VERSION = 1 as const;
export const GENERATED_POLICY_CLIENT_GENERATOR_VERSION = '1.0.0' as const;
export type GeneratedPolicyMethod = 'policy.authorize' | 'policy.verify';

export interface GeneratedPolicyClientTransport {
  request<TMethod extends GeneratedPolicyMethod>(
    method: TMethod,
    payload: CoreServiceMethodPayload<TMethod>
  ): Promise<CoreServiceMethodResult<TMethod>>;
}

export class GeneratedPolicyServiceClient {
  readonly #transport: GeneratedPolicyClientTransport;

  public constructor(transport: GeneratedPolicyClientTransport) {
    if (!transport || typeof transport.request !== 'function') {
      throw new TypeError('Generated policy client transport is unavailable');
    }
    this.#transport = transport;
  }

  public authorize(payload: PolicyAuthorizationContractPayload): Promise<PolicyAuthorizationContractResult> {
    return this.#transport.request('policy.authorize', payload);
  }

  public verify(payload: PolicyReceiptVerificationContractPayload): Promise<PolicyReceiptVerificationContractResult> {
    return this.#transport.request('policy.verify', payload);
  }
}
