import { ERROR_CODES, createAppError, err, type AppError, type Result } from '@ppt/core';
import type { AiConsentApplicationContext, AiConsentQueryPort, AiConsentUnitOfWork, AiConsentWriteScope } from '@ppt/application';
import type { TransactionExecutor, TransactionContext } from '@ppt/repository-contracts';
import type { AccountRepositoryPort, AiConsentRepositoryPort, AuditRepositoryPort, ObjectPermissionRepositoryPort, AccountRow, ObjectPermissionRow, RepositoryExecutionContext } from '@ppt/repository-contracts';
import { CentralAuthorizationService, type AuthorizationAction, type AuthorizationGrant } from '@ppt/security';
export interface RepositoryBackedAiConsentDependencies{readonly transactionExecutor:TransactionExecutor;readonly consentRepository:AiConsentRepositoryPort;readonly accountRepository:AccountRepositoryPort;readonly permissionRepository:ObjectPermissionRepositoryPort;readonly auditRepository:AuditRepositoryPort;}
const rc=(c:AiConsentApplicationContext,t:TransactionContext):RepositoryExecutionContext=>({transaction:t.transaction,actor:{userId:c.actor.userId,roles:[c.actor.role],...(c.actor.personId?{personId:c.actor.personId as never}:{})},correlationId:c.correlationId,occurredAt:t.occurredAt});
const active=(a:AccountRow,at:string)=>a.status==='active'&&Date.parse(a.startsAt)<=Date.parse(at)&&(!a.endsAt||Date.parse(a.endsAt)>=Date.parse(at));
const grant=(r:ObjectPermissionRow):AuthorizationGrant=>({id:r.id,subjectAccountId:r.subjectAccountId,resourceType:r.resourceType,resourceId:r.resourceId,actions:r.actions as readonly AuthorizationAction[],effect:r.effect,purpose:r.purpose,...(r.familyBranchId?{familyBranchId:r.familyBranchId}:{}),...(r.ownershipBasisPoints===undefined?{}:{ownershipBasisPoints:r.ownershipBasisPoints}),...(r.denialReason?{denialReason:r.denialReason}:{}),startsAt:r.startsAt,...(r.endsAt?{endsAt:r.endsAt}:{})});
const load=(d:RepositoryBackedAiConsentDependencies,c:AiConsentApplicationContext,r:RepositoryExecutionContext):Result<{account:AccountRow;grants:readonly AuthorizationGrant[]},AppError>=>{const a=d.accountRepository.findById(r,c.actor.userId);if(!a.ok)return a;if(!a.value||!active(a.value,r.occurredAt))return err(createAppError({code:ERROR_CODES.AUTHORIZATION_DENIED,message:'AI izinleri için etkin üyelik gereklidir.',category:'authorization',correlationId:c.correlationId}));const g=d.permissionRepository.listActiveForSubject(r,c.actor.userId,r.occurredAt);return g.ok?{ok:true,value:{account:a.value,grants:g.value.map(grant)}}:g;};
export class RepositoryBackedAiConsentQueryPort implements AiConsentQueryPort{readonly #auth=new CentralAuthorizationService();constructor(private readonly d:RepositoryBackedAiConsentDependencies){}list(c:AiConsentApplicationContext):ReturnType<AiConsentQueryPort['list']>{return this.d.transactionExecutor.execute(c.correlationId,t=>{const r=rc(c,t),a=load(this.d,c,r);if(!a.ok)return a;return this.d.consentRepository.list(r,c.actor.userId);});}preview(c:AiConsentApplicationContext,purpose:Parameters<AiConsentQueryPort['preview']>[1]):ReturnType<AiConsentQueryPort['preview']>{return this.d.transactionExecutor.execute(c.correlationId,t=>{const r=rc(c,t),a=load(this.d,c,r);if(!a.ok)return a;const cs=this.d.consentRepository.listActive(r,c.actor.userId,purpose,r.occurredAt);if(!cs.ok)return cs;const blocked=this.d.consentRepository.countRevoked(r,c.actor.userId,purpose);if(!blocked.ok)return blocked;const out:Array<{resourceType:string;resourceId:string;title:string}>=[];for(const x of cs.value.filter(x=>x.status==='granted')){const rows=this.d.consentRepository.listAllowedResources(r,x.resourceType,x.resourceId);if(!rows.ok)return rows;for(const item of rows.value){const allowed=this.#auth.authorize({accountId:a.value.account.id,role:a.value.account.role as AiConsentApplicationContext['actor']['role'],action:'read',resourceType:item.resourceType,resourceId:item.resourceId,occurredAt:r.occurredAt,...(a.value.account.personId?{actorPersonId:a.value.account.personId}:{}),grants:a.value.grants}).allowed;if(allowed)out.push(item);}}return {ok:true,value:{purpose,allowedResources:[...new Map(out.map(x=>[`${x.resourceType}:${x.resourceId}`,x])).values()],blockedCount:blocked.value,generatedAt:r.occurredAt}};});}}
class Scope implements AiConsentWriteScope{constructor(private readonly d:RepositoryBackedAiConsentDependencies,private readonly r:RepositoryExecutionContext,public readonly occurredAt:AiConsentWriteScope['occurredAt']){}findIdentity(a:string,p:string,t:string,id:string){return this.d.consentRepository.findIdentity(this.r,a,p,t,id)}upsert(row:Parameters<AiConsentWriteScope['upsert']>[0]){return this.d.consentRepository.upsert(this.r,row)}appendAudit(i:Parameters<AiConsentWriteScope['appendAudit']>[0]){return this.d.auditRepository.append(this.r,i)}}
export class RepositoryBackedAiConsentUnitOfWork implements AiConsentUnitOfWork{constructor(private readonly d:RepositoryBackedAiConsentDependencies){}execute<T>(c:AiConsentApplicationContext,op:(s:AiConsentWriteScope)=>Result<T,AppError>):Result<T,AppError>{return this.d.transactionExecutor.execute(c.correlationId,t=>{const r=rc(c,t),a=load(this.d,c,r);if(!a.ok)return a;return op(new Scope(this.d,r,t.occurredAt));});}}
