import { ERROR_CODES, createAppError, err, type AppError, type Result } from '@ppt/core';
import type { LegacyApplicationContext, LegacyQueryPort, LegacyUnitOfWork, LegacyWriteScope } from '@ppt/application';
import type { TransactionExecutor, TransactionContext } from '@ppt/repository-contracts';
import type { DomainEvent } from '@ppt/events';
import type { AccountRepositoryPort, AuditRepositoryPort, LegacyRepositoryPort, ObjectPermissionRepositoryPort, OutboxRepositoryPort, PersonRepositoryPort, AccountRow, ObjectPermissionRow, RepositoryExecutionContext } from '@ppt/repository-contracts';
import { CentralAuthorizationService, type AuthorizationAction, type AuthorizationGrant } from '@ppt/security';
export interface RepositoryBackedLegacyApplicationDependencies{readonly transactionExecutor:TransactionExecutor;readonly legacyRepository:LegacyRepositoryPort;readonly accountRepository:AccountRepositoryPort;readonly permissionRepository:ObjectPermissionRepositoryPort;readonly personRepository:PersonRepositoryPort;readonly auditRepository:AuditRepositoryPort;readonly outboxRepository:OutboxRepositoryPort;}
const rc=(c:LegacyApplicationContext,t:TransactionContext):RepositoryExecutionContext=>({transaction:t.transaction,actor:{userId:c.actor.userId,roles:[c.actor.role],...(c.actor.personId?{personId:c.actor.personId as never}:{})},correlationId:c.correlationId,occurredAt:t.occurredAt});
const active=(a:AccountRow,at:string)=>a.status==='active'&&Date.parse(a.startsAt)<=Date.parse(at)&&(!a.endsAt||Date.parse(a.endsAt)>=Date.parse(at));
const grant=(r:ObjectPermissionRow):AuthorizationGrant=>({id:r.id,subjectAccountId:r.subjectAccountId,resourceType:r.resourceType,resourceId:r.resourceId,actions:r.actions as readonly AuthorizationAction[],effect:r.effect,purpose:r.purpose,...(r.familyBranchId?{familyBranchId:r.familyBranchId}:{}),...(r.denialReason?{denialReason:r.denialReason}:{}),startsAt:r.startsAt,...(r.endsAt?{endsAt:r.endsAt}:{})});
interface Snapshot{account:AccountRow;grants:readonly AuthorizationGrant[]}
const load=(d:RepositoryBackedLegacyApplicationDependencies,c:LegacyApplicationContext,r:RepositoryExecutionContext):Result<Snapshot,AppError>=>{const a=d.accountRepository.findById(r,c.actor.userId);if(!a.ok)return a;if(!a.value||!active(a.value,r.occurredAt))return err(createAppError({code:ERROR_CODES.AUTHORIZATION_DENIED,message:'Dijital miras işlemleri için etkin üyelik gereklidir.',category:'authorization',correlationId:c.correlationId}));const g=d.permissionRepository.listActiveForSubject(r,c.actor.userId,r.occurredAt);return g.ok?{ok:true,value:{account:a.value,grants:g.value.map(grant)}}:g;};
const allowed=(s:CentralAuthorizationService,x:Snapshot,i:{action:AuthorizationAction;resourceId:string;ownerPersonId:string;occurredAt:string})=>s.authorize({accountId:x.account.id,role:x.account.role as LegacyApplicationContext['actor']['role'],action:i.action,resourceType:'digital_legacy_plan',resourceId:i.resourceId,occurredAt:i.occurredAt,...(x.account.personId?{actorPersonId:x.account.personId}:{}),ownerPersonId:i.ownerPersonId,grants:x.grants}).allowed;
export class RepositoryBackedLegacyQueryPort implements LegacyQueryPort{readonly #auth=new CentralAuthorizationService();constructor(private readonly d:RepositoryBackedLegacyApplicationDependencies){}listPlans(c:LegacyApplicationContext):ReturnType<LegacyQueryPort['listPlans']>{return this.d.transactionExecutor.execute(c.correlationId,t=>{const r=rc(c,t),a=load(this.d,c,r);if(!a.ok)return a;const rows=this.d.legacyRepository.listPlans(r);return rows.ok?{ok:true,value:rows.value.filter(x=>allowed(this.#auth,a.value,{action:'read',resourceId:x.id,ownerPersonId:x.ownerPersonId,occurredAt:r.occurredAt})||x.trusteeAccountId===c.actor.userId||x.secondaryTrusteeAccountId===c.actor.userId)}:rows;});}listGrants(c:LegacyApplicationContext,planId?:string):ReturnType<LegacyQueryPort['listGrants']>{return this.d.transactionExecutor.execute(c.correlationId,t=>{const r=rc(c,t),a=load(this.d,c,r);if(!a.ok)return a;if(planId){const p=this.d.legacyRepository.findPlan(r,planId);if(!p.ok)return p;if(!p.value)return {ok:true,value:[]};const can=allowed(this.#auth,a.value,{action:'read',resourceId:p.value.id,ownerPersonId:p.value.ownerPersonId,occurredAt:r.occurredAt})||p.value.trusteeAccountId===c.actor.userId||p.value.secondaryTrusteeAccountId===c.actor.userId;if(!can)return err(createAppError({code:ERROR_CODES.AUTHORIZATION_DENIED,message:'Yetki paketlerini görüntüleme yetkiniz yok.',category:'authorization',correlationId:c.correlationId}));}return this.d.legacyRepository.listGrants(r,planId);});}listApprovals(c:LegacyApplicationContext,planId:string):ReturnType<LegacyQueryPort['listApprovals']>{return this.d.transactionExecutor.execute(c.correlationId,t=>{const r=rc(c,t),a=load(this.d,c,r);if(!a.ok)return a;const p=this.d.legacyRepository.findPlan(r,planId);if(!p.ok)return p;if(!p.value)return {ok:true,value:[]};const can=allowed(this.#auth,a.value,{action:'read',resourceId:p.value.id,ownerPersonId:p.value.ownerPersonId,occurredAt:r.occurredAt})||p.value.trusteeAccountId===c.actor.userId||p.value.secondaryTrusteeAccountId===c.actor.userId;if(!can)return err(createAppError({code:ERROR_CODES.AUTHORIZATION_DENIED,message:'Onayları görüntüleme yetkiniz yok.',category:'authorization',correlationId:c.correlationId}));return this.d.legacyRepository.listApprovals(r,planId);});}}
class Scope implements LegacyWriteScope{readonly #auth=new CentralAuthorizationService();readonly #snap:Result<Snapshot,AppError>;constructor(private readonly d:RepositoryBackedLegacyApplicationDependencies,private readonly c:LegacyApplicationContext,private readonly r:RepositoryExecutionContext,public readonly occurredAt:LegacyWriteScope['occurredAt']){this.#snap=load(d,c,r);}findPlan(id:string){return this.d.legacyRepository.findPlan(this.r,id);}findPerson(id:string){const x=this.d.personRepository.findById(this.r,id as never);return x.ok?{ok:true as const,value:x.value?{id:x.value.id}:null}:x;}findAccount(id:string){const x=this.d.accountRepository.findById(this.r,id as never);return x.ok?{ok:true as const,value:x.value?{id:x.value.id,status:x.value.status}:null}:x;}authorize(i:Parameters<LegacyWriteScope['authorize']>[0]){if(!this.#snap.ok)return this.#snap;return {ok:true as const,value:allowed(this.#auth,this.#snap.value,{...i,occurredAt:this.r.occurredAt})};}upsertPlan(p:Parameters<LegacyWriteScope['upsertPlan']>[0]){return this.d.legacyRepository.upsertPlan(this.r,p);}listGrants(id:string){return this.d.legacyRepository.listGrants(this.r,id);}upsertGrant(g:Parameters<LegacyWriteScope['upsertGrant']>[0]){return this.d.legacyRepository.upsertGrant(this.r,g);}clearApprovals(id:string){return this.d.legacyRepository.clearApprovals(this.r,id);}upsertApproval(a:Parameters<LegacyWriteScope['upsertApproval']>[0]){return this.d.legacyRepository.upsertApproval(this.r,a);}countApprovals(id:string){return this.d.legacyRepository.countApprovals(this.r,id);}replaceExecutionPermissions(planId:string,subject:Parameters<LegacyWriteScope['replaceExecutionPermissions']>[1],grants:Parameters<LegacyWriteScope['replaceExecutionPermissions']>[2],ids:Parameters<LegacyWriteScope['replaceExecutionPermissions']>[3]){return this.d.legacyRepository.replaceExecutionPermissions(this.r,planId,subject,grants,this.r.occurredAt,ids);}revokeExecutionPermissions(id:string){return this.d.legacyRepository.revokeExecutionPermissions(this.r,id);}appendAudit(i:Parameters<LegacyWriteScope['appendAudit']>[0]){return this.d.auditRepository.append(this.r,i);}enqueueEvent<T>(e:DomainEvent<T>){return this.d.outboxRepository.enqueue(this.r,e);}}
export class RepositoryBackedLegacyUnitOfWork implements LegacyUnitOfWork{constructor(private readonly d:RepositoryBackedLegacyApplicationDependencies){}execute<T>(c:LegacyApplicationContext,op:(s:LegacyWriteScope)=>Result<T,AppError>):Result<T,AppError>{return this.d.transactionExecutor.execute(c.correlationId,t=>op(new Scope(this.d,c,rc(c,t),t.occurredAt)));}}
