import { ERROR_CODES, createAppError, err, ok, type AppError, type CorrelationId, type EventId, type FamilyId, type IsoDateTime, type PersonId, type Result, type UserId } from '@ppt/core';
import { archiveLegacyOwnershipReattestationConfirmation, type ArchiveItemView, type ArchiveSearchInput, type ArchiveVersionView, type ArchiveRetentionPolicyView, type ArchiveRetentionStatusView, type ArchiveCategoryView, type ArchiveClassificationView, type ArchiveSensitivity, type FamilyRole, type LegacyArchiveOwnershipReattestationView, type ReattestLegacyArchiveOwnershipInput } from '@ppt/domain';
import type { DomainEvent } from '@ppt/events';
import { isAdministrativeRole } from '@ppt/security';
import type { StrongAuthenticationPort } from './data-lifecycle-use-cases.js';
export interface ArchiveApplicationContext{readonly familyId:FamilyId;readonly actor:{readonly userId:UserId;readonly role:FamilyRole;readonly personId?:PersonId};readonly correlationId:CorrelationId;readonly operationId?:string;readonly operationFingerprint?:string;}
export interface ArchiveQueryPort{list(c:ArchiveApplicationContext):Promise<Result<readonly ArchiveItemView[],AppError>>;search(c:ArchiveApplicationContext,input:{query:string;categoryId:string;sensitivity:string;tag:string;mimeType:string;linkedEventId:string}):Promise<Result<readonly ArchiveItemView[],AppError>>;getOpenPlan(c:ArchiveApplicationContext,itemId:string):Promise<Result<{storedName:string;sha256:string;originalName:string;mimeType:string;sizeBytes:number;sensitivity:ArchiveSensitivity},AppError>>;listVersions(c:ArchiveApplicationContext,itemId:string):Promise<Result<readonly ArchiveVersionView[],AppError>>;listRetentionPolicies(c:ArchiveApplicationContext):Promise<Result<readonly ArchiveRetentionPolicyView[],AppError>>;listRetentionStatus(c:ArchiveApplicationContext):Promise<Result<readonly ArchiveRetentionStatusView[],AppError>>;getDestructionPlan(c:ArchiveApplicationContext,itemId:string):Promise<Result<{storedName:string;secureDestroy:boolean},AppError>>;listCategories(c:ArchiveApplicationContext):Promise<Result<readonly ArchiveCategoryView[],AppError>>;listClassifications(c:ArchiveApplicationContext):Promise<Result<readonly ArchiveClassificationView[],AppError>>;}
export type ArchivePolicyAction='read'|'create'|'update'|'delete'|'record';
export interface ArchivePolicyIntent{readonly action:ArchivePolicyAction;readonly capability:'archive.read'|'archive.write';readonly resourceType:'archive_collection'|'archive_item'|'archive_retention_policy'|'archive_category';readonly resourceId:string;readonly purpose:'archive';readonly ownershipReattestation?:Readonly<{kind:'legacy_ownerless_to_actor';ownerPersonId:PersonId}>;}
export interface ArchiveWriteScope{readonly occurredAt:IsoDateTime;findOpenPlan(itemId:string):Result<{storedName:string;sha256:string;originalName:string;mimeType:string;sizeBytes:number;sensitivity:ArchiveSensitivity}|null,AppError>;insertRetentionPolicy(i:ArchiveRetentionPolicyView):Result<void,AppError>;assignRetentionPolicy(itemId:string,policyId:string|null):Result<void,AppError>;markDestroyed(itemId:string,destroyedAt:IsoDateTime):Result<void,AppError>;insertItem(i:ArchiveItemView&{familyId:string;storedName:string;sensitivity:'standard'|'personal'|'high';aiProcessingAllowed:boolean}):Result<void,AppError>;insertVersion(v:ArchiveVersionView&{storedName:string}):Result<void,AppError>;incrementEventAttachment(eventId:string):Result<void,AppError>;appendAudit(i:{id:string;action:string;resourceType:string;resourceId:string;occurredAt:IsoDateTime;actorId:UserId}):Result<string,AppError>;enqueueEvent<T>(e:DomainEvent<T>):Result<void,AppError>;insertCategory(i:ArchiveCategoryView):Result<void,AppError>;updateClassification(i:{itemId:string;categoryId:string|null;sensitivity:ArchiveSensitivity;aiProcessingAllowed:boolean;tags:readonly {id:string;name:string}[]}):Result<void,AppError>;reattestLegacyOwnership(itemId:string,ownerPersonId:PersonId):Result<void,AppError>;}
export interface ArchiveUnitOfWork{execute<T>(c:ArchiveApplicationContext,intent:ArchivePolicyIntent,op:(s:ArchiveWriteScope)=>Result<T,AppError>):Promise<Result<T,AppError>>}
const invalid=(c:ArchiveApplicationContext,m:string)=>createAppError({code:ERROR_CODES.CORE_INVALID_ARGUMENT,message:m,category:'validation',correlationId:c.correlationId});
export class ListArchiveItemsUseCase{constructor(private readonly q:ArchiveQueryPort){}execute(c:ArchiveApplicationContext){return this.q.list(c)}}
export class SearchArchiveItemsUseCase{constructor(private readonly q:ArchiveQueryPort){}execute(c:ArchiveApplicationContext,input:ArchiveSearchInput={}){const sensitivity=input.sensitivity??'';if(sensitivity&&!['standard','personal','high'].includes(sensitivity))return err(invalid(c,'Arşiv hassasiyet seviyesi geçersizdir.'));const normalized={query:(input.query??'').trim().toLocaleLowerCase('tr-TR'),categoryId:(input.categoryId??'').trim(),sensitivity,tag:(input.tag??'').trim().toLocaleLowerCase('tr-TR'),mimeType:(input.mimeType??'').trim(),linkedEventId:(input.linkedEventId??'').trim()};return this.q.search(c,normalized)}}
export class PrepareArchiveOpenUseCase{constructor(private readonly q:ArchiveQueryPort){}execute(c:ArchiveApplicationContext,itemId:string){const id=itemId.trim();if(!id)return err(invalid(c,'Arşiv kaydı kimliği zorunludur.'));return this.q.getOpenPlan(c,id)}}
export class ListArchiveVersionsUseCase{constructor(private readonly q:ArchiveQueryPort){}execute(c:ArchiveApplicationContext,itemId:string){return this.q.listVersions(c,itemId)}}
export class ImportArchiveItemUseCase{constructor(private readonly u:ArchiveUnitOfWork){}async execute(i:{context:ArchiveApplicationContext;command:{title:string;originalName:string;storedName:string;mimeType:string;sizeBytes:number;sha256:string;linkedEventId?:string};identifiers:{itemId:string;versionId:string;auditId:string;outboxEventId:EventId}}):Promise<Result<ArchiveItemView,AppError>>{const title=i.command.title.trim();if(title.length<2)return err(invalid(i.context,'Arşiv başlığı en az 2 karakter olmalıdır.'));if(!Number.isInteger(i.command.sizeBytes)||i.command.sizeBytes<1||i.command.sizeBytes>250*1024*1024)return err(invalid(i.context,'Dosya boyutu geçersiz.'));if(!/^[a-f0-9]{64}$/i.test(i.command.sha256))return err(invalid(i.context,'Dosya özeti geçersiz.'));return this.u.execute(i.context,{action:'create',capability:'archive.write',resourceType:'archive_item',resourceId:i.identifiers.itemId,purpose:'archive'},s=>{const item={id:i.identifiers.itemId,title,originalName:i.command.originalName,mimeType:i.command.mimeType,sizeBytes:i.command.sizeBytes,sha256:i.command.sha256,createdAt:s.occurredAt,...(i.command.linkedEventId?{linkedEventId:i.command.linkedEventId}:{})};const x=s.insertItem({...item,familyId:i.context.familyId,storedName:i.command.storedName,sensitivity:'standard',aiProcessingAllowed:false});if(!x.ok)return x;if(i.command.linkedEventId){const y=s.incrementEventAttachment(i.command.linkedEventId);if(!y.ok)return y;}const v=s.insertVersion({id:i.identifiers.versionId,archiveItemId:item.id,versionNo:1,originalName:item.originalName,storedName:i.command.storedName,mimeType:item.mimeType,sizeBytes:item.sizeBytes,sha256:item.sha256,createdAt:s.occurredAt,note:'İlk sürüm'});if(!v.ok)return v;const au=s.appendAudit({id:i.identifiers.auditId,action:'archive.imported',resourceType:'archive_item',resourceId:item.id,occurredAt:s.occurredAt,actorId:i.context.actor.userId});if(!au.ok)return au;const ev=s.enqueueEvent({eventId:i.identifiers.outboxEventId,eventType:'archive.item.imported',eventVersion:1,aggregateType:'archive_item',aggregateId:item.id,occurredAt:s.occurredAt,actorId:i.context.actor.userId,correlationId:i.context.correlationId,payload:{itemId:item.id,sha256:item.sha256,sizeBytes:item.sizeBytes}});return ev.ok?ok(item):ev;});}}

export class ListArchiveRetentionPoliciesUseCase{constructor(private readonly q:ArchiveQueryPort){}execute(c:ArchiveApplicationContext){return this.q.listRetentionPolicies(c)}}
export class ListArchiveRetentionStatusUseCase{constructor(private readonly q:ArchiveQueryPort){}execute(c:ArchiveApplicationContext){return this.q.listRetentionStatus(c)}}
export class CreateArchiveRetentionPolicyUseCase{constructor(private readonly u:ArchiveUnitOfWork){}async execute(i:{context:ArchiveApplicationContext;command:{name:string;retentionDays:number;secureDestroy:boolean};identifiers:{policyId:string;auditId:string}}):Promise<Result<ArchiveRetentionPolicyView,AppError>>{const name=i.command.name.trim();if(name.length<2||name.length>100)return err(invalid(i.context,'Politika adı 2 ile 100 karakter arasında olmalıdır.'));if(!Number.isInteger(i.command.retentionDays)||i.command.retentionDays<1||i.command.retentionDays>36500)return err(invalid(i.context,'Saklama süresi 1-36500 gün olmalıdır.'));return this.u.execute(i.context,{action:'create',capability:'archive.write',resourceType:'archive_retention_policy',resourceId:i.identifiers.policyId,purpose:'archive'},s=>{const row={id:i.identifiers.policyId,name,retentionDays:i.command.retentionDays,secureDestroy:i.command.secureDestroy,createdAt:s.occurredAt};const x=s.insertRetentionPolicy(row);if(!x.ok)return x;const a=s.appendAudit({id:i.identifiers.auditId,action:'archive.retention_policy_created',resourceType:'archive_retention_policy',resourceId:row.id,occurredAt:s.occurredAt,actorId:i.context.actor.userId});return a.ok?ok(row):a;});}}
export class AssignArchiveRetentionPolicyUseCase{constructor(private readonly u:ArchiveUnitOfWork){}async execute(i:{context:ArchiveApplicationContext;itemId:string;policyId?:string;identifiers:{auditId:string}}):Promise<Result<void,AppError>>{return this.u.execute(i.context,{action:'update',capability:'archive.write',resourceType:'archive_item',resourceId:i.itemId,purpose:'archive'},s=>{const x=s.assignRetentionPolicy(i.itemId,i.policyId??null);if(!x.ok)return x;const au=s.appendAudit({id:i.identifiers.auditId,action:'archive.retention_policy_assigned',resourceType:'archive_item',resourceId:i.itemId,occurredAt:s.occurredAt,actorId:i.context.actor.userId});return au.ok?ok(undefined):au;});}}
export class PrepareArchiveDestructionUseCase{constructor(private readonly q:ArchiveQueryPort){}async execute(c:ArchiveApplicationContext,itemId:string):Promise<Result<{storedName:string;secureDestroy:boolean},AppError>>{const id=itemId.trim();if(!id)return err(invalid(c,'Arşiv kaydı kimliği zorunludur.'));return this.q.getDestructionPlan(c,id)}}
export class RecordArchiveOpenedUseCase{constructor(private readonly u:ArchiveUnitOfWork){}async execute(i:{context:ArchiveApplicationContext;itemId:string;identifiers:{auditId:string}}):Promise<Result<void,AppError>>{return this.u.execute(i.context,{action:'record',capability:'archive.write',resourceType:'archive_item',resourceId:i.itemId,purpose:'archive'},s=>{const au=s.appendAudit({id:i.identifiers.auditId,action:'archive.opened',resourceType:'archive_item',resourceId:i.itemId,occurredAt:s.occurredAt,actorId:i.context.actor.userId});return au.ok?ok(undefined):au;});}}
export type EmergencyArchiveReadAuthorization =
  | Readonly<{state:'authorized';storedName:string;sha256:string;originalName:string;mimeType:string;sizeBytes:number;sensitivity:'high'}>
  | Readonly<{state:'denied';reason:'not_found'|'sensitivity'|'size'}>;
export class AuthorizeEmergencyArchiveReadUseCase{constructor(private readonly u:ArchiveUnitOfWork){}async execute(i:{context:ArchiveApplicationContext;itemId:string;identifiers:{auditId:string}}):Promise<Result<EmergencyArchiveReadAuthorization,AppError>>{const itemId=i.itemId.trim();if(!itemId)return err(invalid(i.context,'Acil kart arşiv kaydı kimliği zorunludur.'));return this.u.execute<EmergencyArchiveReadAuthorization>(i.context,{action:'record',capability:'archive.write',resourceType:'archive_item',resourceId:itemId,purpose:'archive'},s=>{const plan=s.findOpenPlan(itemId);if(!plan.ok)return plan;if(!plan.value)return ok({state:'denied',reason:'not_found'});if(plan.value.sensitivity!=='high')return ok({state:'denied',reason:'sensitivity'});if(!Number.isInteger(plan.value.sizeBytes)||plan.value.sizeBytes<1||plan.value.sizeBytes>10*1024*1024)return ok({state:'denied',reason:'size'});const audit=s.appendAudit({id:i.identifiers.auditId,action:'archive.emergency_export_read_authorized',resourceType:'archive_item',resourceId:itemId,occurredAt:s.occurredAt,actorId:i.context.actor.userId});return audit.ok?ok({state:'authorized',...plan.value,sensitivity:'high'}):audit;});}}
export class MarkArchiveDestroyedUseCase{constructor(private readonly u:ArchiveUnitOfWork){}async execute(i:{context:ArchiveApplicationContext;itemId:string;identifiers:{auditId:string}}):Promise<Result<void,AppError>>{return this.u.execute(i.context,{action:'delete',capability:'archive.write',resourceType:'archive_item',resourceId:i.itemId,purpose:'archive'},s=>{const x=s.markDestroyed(i.itemId,s.occurredAt);if(!x.ok)return x;const a=s.appendAudit({id:i.identifiers.auditId,action:'archive.secure_destroyed',resourceType:'archive_item',resourceId:i.itemId,occurredAt:s.occurredAt,actorId:i.context.actor.userId});return a.ok?ok(undefined):a;});}}

export class ReattestLegacyArchiveOwnershipUseCase {
  public constructor(private readonly unit:ArchiveUnitOfWork,private readonly strongAuthentication:StrongAuthenticationPort){}
  public async execute(input:{context:ArchiveApplicationContext;command:ReattestLegacyArchiveOwnershipInput;identifiers:{auditId:string;outboxEventId:EventId}}):Promise<Result<LegacyArchiveOwnershipReattestationView,AppError>>{
    const itemId=input.command.itemId.trim();
    if(!itemId||itemId.length>256)return err(invalid(input.context,'Arşiv kaydı kimliği geçersizdir.'));
    const actorPersonId=input.context.actor.personId;
    if(!actorPersonId||!isAdministrativeRole(input.context.actor.role))return err(createAppError({code:ERROR_CODES.AUTHORIZATION_DENIED,message:'Eski arşiv sahipliğini yalnız kişi profiline bağlı aile yöneticisi yeniden doğrulayabilir.',category:'authorization',correlationId:input.context.correlationId}));
    if(input.command.confirmation!==archiveLegacyOwnershipReattestationConfirmation(itemId))return err(invalid(input.context,'Eski arşiv sahipliği onay metni birebir eşleşmelidir.'));
    if(input.command.password.length<1||input.command.password.length>1024||(input.command.code!==undefined&&!/^\d{6,10}$/u.test(input.command.code)))return err(invalid(input.context,'Güçlü kimlik doğrulama girdisi geçersizdir.'));
    const verified=this.strongAuthentication.verify(input.context,{password:input.command.password,...(input.command.code?{code:input.command.code}:{})});
    if(!verified.ok)return verified;
    const ownerPersonId=actorPersonId;
    return this.unit.execute(input.context,{action:'update',capability:'archive.write',resourceType:'archive_item',resourceId:itemId,purpose:'archive',ownershipReattestation:{kind:'legacy_ownerless_to_actor',ownerPersonId}},scope=>{
      const saved=scope.reattestLegacyOwnership(itemId,ownerPersonId);if(!saved.ok)return saved;
      const audit=scope.appendAudit({id:input.identifiers.auditId,action:'archive.legacy_ownership_reattested',resourceType:'archive_item',resourceId:itemId,occurredAt:scope.occurredAt,actorId:input.context.actor.userId});if(!audit.ok)return audit;
      const event=scope.enqueueEvent({eventId:input.identifiers.outboxEventId,eventType:'archive.legacy_ownership_reattested',eventVersion:1,aggregateType:'archive_item',aggregateId:itemId,occurredAt:scope.occurredAt,actorId:input.context.actor.userId,correlationId:input.context.correlationId,payload:{itemId,ownershipBinding:'verified_actor',confirmationVersion:1}});if(!event.ok)return event;
      return ok({itemId,ownershipBinding:'verified_actor',reattestedAt:scope.occurredAt});
    });
  }
}

export class ListArchiveCategoriesUseCase{constructor(private readonly q:ArchiveQueryPort){}execute(c:ArchiveApplicationContext){return this.q.listCategories(c)}}
export class ListArchiveClassificationsUseCase{constructor(private readonly q:ArchiveQueryPort){}execute(c:ArchiveApplicationContext){return this.q.listClassifications(c)}}
export class CreateArchiveCategoryUseCase{constructor(private readonly u:ArchiveUnitOfWork){}async execute(i:{context:ArchiveApplicationContext;command:{name:string;description?:string};identifiers:{categoryId:string;auditId:string}}):Promise<Result<ArchiveCategoryView,AppError>>{const name=i.command.name.trim();if(name.length<2||name.length>80)return err(invalid(i.context,'Kategori adı 2 ile 80 karakter arasında olmalıdır.'));const description=i.command.description?.trim();if(description&&description.length>500)return err(invalid(i.context,'Kategori açıklaması 500 karakteri geçemez.'));return this.u.execute(i.context,{action:'create',capability:'archive.write',resourceType:'archive_category',resourceId:i.identifiers.categoryId,purpose:'archive'},s=>{const row:ArchiveCategoryView={id:i.identifiers.categoryId,name,...(description?{description}:{}) ,createdAt:s.occurredAt};const x=s.insertCategory(row);if(!x.ok)return x;const a=s.appendAudit({id:i.identifiers.auditId,action:'archive.category_created',resourceType:'archive_category',resourceId:row.id,occurredAt:s.occurredAt,actorId:i.context.actor.userId});return a.ok?ok(row):a;});}}
export class UpdateArchiveClassificationUseCase{constructor(private readonly u:ArchiveUnitOfWork){}async execute(i:{context:ArchiveApplicationContext;command:{itemId:string;categoryId?:string;tagNames:readonly string[];sensitivity:ArchiveSensitivity;aiProcessingAllowed:boolean};identifiers:{auditId:string;tagIds:readonly string[]}}):Promise<Result<void,AppError>>{const itemId=i.command.itemId.trim();if(!itemId)return err(invalid(i.context,'Arşiv kaydı kimliği zorunludur.'));if(!['standard','personal','high'].includes(i.command.sensitivity))return err(invalid(i.context,'Arşiv hassasiyet seviyesi geçersizdir.'));const seen=new Set<string>();const names=i.command.tagNames.map(x=>x.trim()).filter(x=>{if(!x)return false;const key=x.toLocaleLowerCase('tr-TR');if(seen.has(key))return false;seen.add(key);return true;}).slice(0,20);if(names.some(x=>x.length>80))return err(invalid(i.context,'Etiket adı 80 karakteri geçemez.'));if(i.identifiers.tagIds.length<names.length)return err(invalid(i.context,'Etiket kimlikleri eksik.'));return this.u.execute(i.context,{action:'update',capability:'archive.write',resourceType:'archive_item',resourceId:itemId,purpose:'archive'},s=>{const x=s.updateClassification({itemId,categoryId:i.command.categoryId?.trim()||null,sensitivity:i.command.sensitivity,aiProcessingAllowed:i.command.aiProcessingAllowed,tags:names.map((name,index)=>({id:i.identifiers.tagIds[index]!,name}))});if(!x.ok)return x;const au=s.appendAudit({id:i.identifiers.auditId,action:'archive.classification_updated',resourceType:'archive_item',resourceId:itemId,occurredAt:s.occurredAt,actorId:i.context.actor.userId});return au.ok?ok(undefined):au;});}}
